// Code generated by ent, DO NOT EDIT.

package ticket

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ticket type in the database.
	Label = "ticket"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUserUnreadCount holds the string denoting the user_unread_count field in the database.
	FieldUserUnreadCount = "user_unread_count"
	// FieldAdminUnreadCount holds the string denoting the admin_unread_count field in the database.
	FieldAdminUnreadCount = "admin_unread_count"
	// FieldLastActorType holds the string denoting the last_actor_type field in the database.
	FieldLastActorType = "last_actor_type"
	// FieldLastMessageAt holds the string denoting the last_message_at field in the database.
	FieldLastMessageAt = "last_message_at"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// FieldClosedByUserID holds the string denoting the closed_by_user_id field in the database.
	FieldClosedByUserID = "closed_by_user_id"
	// FieldClosedByRole holds the string denoting the closed_by_role field in the database.
	FieldClosedByRole = "closed_by_role"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// Table holds the table name of the ticket in the database.
	Table = "tickets"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "tickets"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "tickets"
	// CategoryInverseTable is the table name for the TicketCategory entity.
	// It exists in this package in order to avoid circular dependency with the "ticketcategory" package.
	CategoryInverseTable = "ticket_categories"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "category_id"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "ticket_messages"
	// MessagesInverseTable is the table name for the TicketMessage entity.
	// It exists in this package in order to avoid circular dependency with the "ticketmessage" package.
	MessagesInverseTable = "ticket_messages"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "ticket_id"
)

// Columns holds all SQL columns for ticket fields.
var Columns = []string{
	FieldID,
	FieldNumber,
	FieldUserID,
	FieldCategoryID,
	FieldSubject,
	FieldStatus,
	FieldUserUnreadCount,
	FieldAdminUnreadCount,
	FieldLastActorType,
	FieldLastMessageAt,
	FieldClosedAt,
	FieldClosedByUserID,
	FieldClosedByRole,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NumberValidator is a validator for the "number" field. It is called by the builders before save.
	NumberValidator func(string) error
	// SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	SubjectValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultUserUnreadCount holds the default value on creation for the "user_unread_count" field.
	DefaultUserUnreadCount int
	// DefaultAdminUnreadCount holds the default value on creation for the "admin_unread_count" field.
	DefaultAdminUnreadCount int
	// DefaultLastActorType holds the default value on creation for the "last_actor_type" field.
	DefaultLastActorType string
	// LastActorTypeValidator is a validator for the "last_actor_type" field. It is called by the builders before save.
	LastActorTypeValidator func(string) error
	// DefaultLastMessageAt holds the default value on creation for the "last_message_at" field.
	DefaultLastMessageAt func() time.Time
	// ClosedByRoleValidator is a validator for the "closed_by_role" field. It is called by the builders before save.
	ClosedByRoleValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Ticket queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCategoryID orders the results by the category_id field.
func ByCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryID, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUserUnreadCount orders the results by the user_unread_count field.
func ByUserUnreadCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserUnreadCount, opts...).ToFunc()
}

// ByAdminUnreadCount orders the results by the admin_unread_count field.
func ByAdminUnreadCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminUnreadCount, opts...).ToFunc()
}

// ByLastActorType orders the results by the last_actor_type field.
func ByLastActorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastActorType, opts...).ToFunc()
}

// ByLastMessageAt orders the results by the last_message_at field.
func ByLastMessageAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageAt, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}

// ByClosedByUserID orders the results by the closed_by_user_id field.
func ByClosedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedByUserID, opts...).ToFunc()
}

// ByClosedByRole orders the results by the closed_by_role field.
func ByClosedByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedByRole, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
	)
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
	)
}
