// Code generated by ent, DO NOT EDIT.

package appoauthgrant

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the appoauthgrant type in the database.
	Label = "app_oauth_grant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldGrantID holds the string denoting the grant_id field in the database.
	FieldGrantID = "grant_id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldGrantVersion holds the string denoting the grant_version field in the database.
	FieldGrantVersion = "grant_version"
	// FieldFirstAuthorizedAt holds the string denoting the first_authorized_at field in the database.
	FieldFirstAuthorizedAt = "first_authorized_at"
	// FieldLastAuthorizedAt holds the string denoting the last_authorized_at field in the database.
	FieldLastAuthorizedAt = "last_authorized_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// Table holds the table name of the appoauthgrant in the database.
	Table = "app_oauth_grants"
)

// Columns holds all SQL columns for appoauthgrant fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldGrantID,
	FieldClientID,
	FieldScopes,
	FieldStatus,
	FieldGrantVersion,
	FieldFirstAuthorizedAt,
	FieldLastAuthorizedAt,
	FieldRevokedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// GrantIDValidator is a validator for the "grant_id" field. It is called by the builders before save.
	GrantIDValidator func(string) error
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// DefaultScopes holds the default value on creation for the "scopes" field.
	DefaultScopes func() []string
	// DefaultGrantVersion holds the default value on creation for the "grant_version" field.
	DefaultGrantVersion int
	// GrantVersionValidator is a validator for the "grant_version" field. It is called by the builders before save.
	GrantVersionValidator func(int) error
	// DefaultFirstAuthorizedAt holds the default value on creation for the "first_authorized_at" field.
	DefaultFirstAuthorizedAt func() time.Time
	// DefaultLastAuthorizedAt holds the default value on creation for the "last_authorized_at" field.
	DefaultLastAuthorizedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive  Status = "active"
	StatusRevoked Status = "revoked"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusRevoked:
		return nil
	default:
		return fmt.Errorf("appoauthgrant: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AppOAuthGrant queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByGrantID orders the results by the grant_id field.
func ByGrantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByGrantVersion orders the results by the grant_version field.
func ByGrantVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantVersion, opts...).ToFunc()
}

// ByFirstAuthorizedAt orders the results by the first_authorized_at field.
func ByFirstAuthorizedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstAuthorizedAt, opts...).ToFunc()
}

// ByLastAuthorizedAt orders the results by the last_authorized_at field.
func ByLastAuthorizedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastAuthorizedAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}
