// Code generated by ent, DO NOT EDIT.

package appoauthgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldUserID, v))
}

// GrantID applies equality check predicate on the "grant_id" field. It's identical to GrantIDEQ.
func GrantID(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldGrantID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldClientID, v))
}

// GrantVersion applies equality check predicate on the "grant_version" field. It's identical to GrantVersionEQ.
func GrantVersion(v int) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldGrantVersion, v))
}

// FirstAuthorizedAt applies equality check predicate on the "first_authorized_at" field. It's identical to FirstAuthorizedAtEQ.
func FirstAuthorizedAt(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldFirstAuthorizedAt, v))
}

// LastAuthorizedAt applies equality check predicate on the "last_authorized_at" field. It's identical to LastAuthorizedAtEQ.
func LastAuthorizedAt(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldLastAuthorizedAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLTE(FieldUserID, v))
}

// GrantIDEQ applies the EQ predicate on the "grant_id" field.
func GrantIDEQ(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldGrantID, v))
}

// GrantIDNEQ applies the NEQ predicate on the "grant_id" field.
func GrantIDNEQ(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNEQ(FieldGrantID, v))
}

// GrantIDIn applies the In predicate on the "grant_id" field.
func GrantIDIn(vs ...string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldIn(FieldGrantID, vs...))
}

// GrantIDNotIn applies the NotIn predicate on the "grant_id" field.
func GrantIDNotIn(vs ...string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNotIn(FieldGrantID, vs...))
}

// GrantIDGT applies the GT predicate on the "grant_id" field.
func GrantIDGT(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGT(FieldGrantID, v))
}

// GrantIDGTE applies the GTE predicate on the "grant_id" field.
func GrantIDGTE(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGTE(FieldGrantID, v))
}

// GrantIDLT applies the LT predicate on the "grant_id" field.
func GrantIDLT(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLT(FieldGrantID, v))
}

// GrantIDLTE applies the LTE predicate on the "grant_id" field.
func GrantIDLTE(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLTE(FieldGrantID, v))
}

// GrantIDContains applies the Contains predicate on the "grant_id" field.
func GrantIDContains(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldContains(FieldGrantID, v))
}

// GrantIDHasPrefix applies the HasPrefix predicate on the "grant_id" field.
func GrantIDHasPrefix(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldHasPrefix(FieldGrantID, v))
}

// GrantIDHasSuffix applies the HasSuffix predicate on the "grant_id" field.
func GrantIDHasSuffix(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldHasSuffix(FieldGrantID, v))
}

// GrantIDEqualFold applies the EqualFold predicate on the "grant_id" field.
func GrantIDEqualFold(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEqualFold(FieldGrantID, v))
}

// GrantIDContainsFold applies the ContainsFold predicate on the "grant_id" field.
func GrantIDContainsFold(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldContainsFold(FieldGrantID, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldContainsFold(FieldClientID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNotIn(FieldStatus, vs...))
}

// GrantVersionEQ applies the EQ predicate on the "grant_version" field.
func GrantVersionEQ(v int) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldGrantVersion, v))
}

// GrantVersionNEQ applies the NEQ predicate on the "grant_version" field.
func GrantVersionNEQ(v int) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNEQ(FieldGrantVersion, v))
}

// GrantVersionIn applies the In predicate on the "grant_version" field.
func GrantVersionIn(vs ...int) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldIn(FieldGrantVersion, vs...))
}

// GrantVersionNotIn applies the NotIn predicate on the "grant_version" field.
func GrantVersionNotIn(vs ...int) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNotIn(FieldGrantVersion, vs...))
}

// GrantVersionGT applies the GT predicate on the "grant_version" field.
func GrantVersionGT(v int) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGT(FieldGrantVersion, v))
}

// GrantVersionGTE applies the GTE predicate on the "grant_version" field.
func GrantVersionGTE(v int) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGTE(FieldGrantVersion, v))
}

// GrantVersionLT applies the LT predicate on the "grant_version" field.
func GrantVersionLT(v int) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLT(FieldGrantVersion, v))
}

// GrantVersionLTE applies the LTE predicate on the "grant_version" field.
func GrantVersionLTE(v int) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLTE(FieldGrantVersion, v))
}

// FirstAuthorizedAtEQ applies the EQ predicate on the "first_authorized_at" field.
func FirstAuthorizedAtEQ(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldFirstAuthorizedAt, v))
}

// FirstAuthorizedAtNEQ applies the NEQ predicate on the "first_authorized_at" field.
func FirstAuthorizedAtNEQ(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNEQ(FieldFirstAuthorizedAt, v))
}

// FirstAuthorizedAtIn applies the In predicate on the "first_authorized_at" field.
func FirstAuthorizedAtIn(vs ...time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldIn(FieldFirstAuthorizedAt, vs...))
}

// FirstAuthorizedAtNotIn applies the NotIn predicate on the "first_authorized_at" field.
func FirstAuthorizedAtNotIn(vs ...time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNotIn(FieldFirstAuthorizedAt, vs...))
}

// FirstAuthorizedAtGT applies the GT predicate on the "first_authorized_at" field.
func FirstAuthorizedAtGT(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGT(FieldFirstAuthorizedAt, v))
}

// FirstAuthorizedAtGTE applies the GTE predicate on the "first_authorized_at" field.
func FirstAuthorizedAtGTE(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGTE(FieldFirstAuthorizedAt, v))
}

// FirstAuthorizedAtLT applies the LT predicate on the "first_authorized_at" field.
func FirstAuthorizedAtLT(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLT(FieldFirstAuthorizedAt, v))
}

// FirstAuthorizedAtLTE applies the LTE predicate on the "first_authorized_at" field.
func FirstAuthorizedAtLTE(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLTE(FieldFirstAuthorizedAt, v))
}

// LastAuthorizedAtEQ applies the EQ predicate on the "last_authorized_at" field.
func LastAuthorizedAtEQ(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldLastAuthorizedAt, v))
}

// LastAuthorizedAtNEQ applies the NEQ predicate on the "last_authorized_at" field.
func LastAuthorizedAtNEQ(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNEQ(FieldLastAuthorizedAt, v))
}

// LastAuthorizedAtIn applies the In predicate on the "last_authorized_at" field.
func LastAuthorizedAtIn(vs ...time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldIn(FieldLastAuthorizedAt, vs...))
}

// LastAuthorizedAtNotIn applies the NotIn predicate on the "last_authorized_at" field.
func LastAuthorizedAtNotIn(vs ...time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNotIn(FieldLastAuthorizedAt, vs...))
}

// LastAuthorizedAtGT applies the GT predicate on the "last_authorized_at" field.
func LastAuthorizedAtGT(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGT(FieldLastAuthorizedAt, v))
}

// LastAuthorizedAtGTE applies the GTE predicate on the "last_authorized_at" field.
func LastAuthorizedAtGTE(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGTE(FieldLastAuthorizedAt, v))
}

// LastAuthorizedAtLT applies the LT predicate on the "last_authorized_at" field.
func LastAuthorizedAtLT(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLT(FieldLastAuthorizedAt, v))
}

// LastAuthorizedAtLTE applies the LTE predicate on the "last_authorized_at" field.
func LastAuthorizedAtLTE(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLTE(FieldLastAuthorizedAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.FieldNotNull(FieldRevokedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppOAuthGrant) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppOAuthGrant) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppOAuthGrant) predicate.AppOAuthGrant {
	return predicate.AppOAuthGrant(sql.NotPredicates(p))
}
