// Code generated by ent, DO NOT EDIT.

package appoauthsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// AppGrantID applies equality check predicate on the "app_grant_id" field. It's identical to AppGrantIDEQ.
func AppGrantID(v int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldAppGrantID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldSessionID, v))
}

// InstallationIDHash applies equality check predicate on the "installation_id_hash" field. It's identical to InstallationIDHashEQ.
func InstallationIDHash(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldInstallationIDHash, v))
}

// TokenFamilyID applies equality check predicate on the "token_family_id" field. It's identical to TokenFamilyIDEQ.
func TokenFamilyID(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldTokenFamilyID, v))
}

// DeviceName applies equality check predicate on the "device_name" field. It's identical to DeviceNameEQ.
func DeviceName(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldDeviceName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldPlatform, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldLastUsedAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// AppGrantIDEQ applies the EQ predicate on the "app_grant_id" field.
func AppGrantIDEQ(v int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldAppGrantID, v))
}

// AppGrantIDNEQ applies the NEQ predicate on the "app_grant_id" field.
func AppGrantIDNEQ(v int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNEQ(FieldAppGrantID, v))
}

// AppGrantIDIn applies the In predicate on the "app_grant_id" field.
func AppGrantIDIn(vs ...int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIn(FieldAppGrantID, vs...))
}

// AppGrantIDNotIn applies the NotIn predicate on the "app_grant_id" field.
func AppGrantIDNotIn(vs ...int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotIn(FieldAppGrantID, vs...))
}

// AppGrantIDGT applies the GT predicate on the "app_grant_id" field.
func AppGrantIDGT(v int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGT(FieldAppGrantID, v))
}

// AppGrantIDGTE applies the GTE predicate on the "app_grant_id" field.
func AppGrantIDGTE(v int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGTE(FieldAppGrantID, v))
}

// AppGrantIDLT applies the LT predicate on the "app_grant_id" field.
func AppGrantIDLT(v int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLT(FieldAppGrantID, v))
}

// AppGrantIDLTE applies the LTE predicate on the "app_grant_id" field.
func AppGrantIDLTE(v int64) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLTE(FieldAppGrantID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldContainsFold(FieldSessionID, v))
}

// InstallationIDHashEQ applies the EQ predicate on the "installation_id_hash" field.
func InstallationIDHashEQ(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldInstallationIDHash, v))
}

// InstallationIDHashNEQ applies the NEQ predicate on the "installation_id_hash" field.
func InstallationIDHashNEQ(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNEQ(FieldInstallationIDHash, v))
}

// InstallationIDHashIn applies the In predicate on the "installation_id_hash" field.
func InstallationIDHashIn(vs ...string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIn(FieldInstallationIDHash, vs...))
}

// InstallationIDHashNotIn applies the NotIn predicate on the "installation_id_hash" field.
func InstallationIDHashNotIn(vs ...string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotIn(FieldInstallationIDHash, vs...))
}

// InstallationIDHashGT applies the GT predicate on the "installation_id_hash" field.
func InstallationIDHashGT(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGT(FieldInstallationIDHash, v))
}

// InstallationIDHashGTE applies the GTE predicate on the "installation_id_hash" field.
func InstallationIDHashGTE(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGTE(FieldInstallationIDHash, v))
}

// InstallationIDHashLT applies the LT predicate on the "installation_id_hash" field.
func InstallationIDHashLT(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLT(FieldInstallationIDHash, v))
}

// InstallationIDHashLTE applies the LTE predicate on the "installation_id_hash" field.
func InstallationIDHashLTE(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLTE(FieldInstallationIDHash, v))
}

// InstallationIDHashContains applies the Contains predicate on the "installation_id_hash" field.
func InstallationIDHashContains(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldContains(FieldInstallationIDHash, v))
}

// InstallationIDHashHasPrefix applies the HasPrefix predicate on the "installation_id_hash" field.
func InstallationIDHashHasPrefix(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldHasPrefix(FieldInstallationIDHash, v))
}

// InstallationIDHashHasSuffix applies the HasSuffix predicate on the "installation_id_hash" field.
func InstallationIDHashHasSuffix(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldHasSuffix(FieldInstallationIDHash, v))
}

// InstallationIDHashEqualFold applies the EqualFold predicate on the "installation_id_hash" field.
func InstallationIDHashEqualFold(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEqualFold(FieldInstallationIDHash, v))
}

// InstallationIDHashContainsFold applies the ContainsFold predicate on the "installation_id_hash" field.
func InstallationIDHashContainsFold(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldContainsFold(FieldInstallationIDHash, v))
}

// TokenFamilyIDEQ applies the EQ predicate on the "token_family_id" field.
func TokenFamilyIDEQ(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldTokenFamilyID, v))
}

// TokenFamilyIDNEQ applies the NEQ predicate on the "token_family_id" field.
func TokenFamilyIDNEQ(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNEQ(FieldTokenFamilyID, v))
}

// TokenFamilyIDIn applies the In predicate on the "token_family_id" field.
func TokenFamilyIDIn(vs ...string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIn(FieldTokenFamilyID, vs...))
}

// TokenFamilyIDNotIn applies the NotIn predicate on the "token_family_id" field.
func TokenFamilyIDNotIn(vs ...string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotIn(FieldTokenFamilyID, vs...))
}

// TokenFamilyIDGT applies the GT predicate on the "token_family_id" field.
func TokenFamilyIDGT(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGT(FieldTokenFamilyID, v))
}

// TokenFamilyIDGTE applies the GTE predicate on the "token_family_id" field.
func TokenFamilyIDGTE(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGTE(FieldTokenFamilyID, v))
}

// TokenFamilyIDLT applies the LT predicate on the "token_family_id" field.
func TokenFamilyIDLT(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLT(FieldTokenFamilyID, v))
}

// TokenFamilyIDLTE applies the LTE predicate on the "token_family_id" field.
func TokenFamilyIDLTE(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLTE(FieldTokenFamilyID, v))
}

// TokenFamilyIDContains applies the Contains predicate on the "token_family_id" field.
func TokenFamilyIDContains(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldContains(FieldTokenFamilyID, v))
}

// TokenFamilyIDHasPrefix applies the HasPrefix predicate on the "token_family_id" field.
func TokenFamilyIDHasPrefix(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldHasPrefix(FieldTokenFamilyID, v))
}

// TokenFamilyIDHasSuffix applies the HasSuffix predicate on the "token_family_id" field.
func TokenFamilyIDHasSuffix(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldHasSuffix(FieldTokenFamilyID, v))
}

// TokenFamilyIDEqualFold applies the EqualFold predicate on the "token_family_id" field.
func TokenFamilyIDEqualFold(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEqualFold(FieldTokenFamilyID, v))
}

// TokenFamilyIDContainsFold applies the ContainsFold predicate on the "token_family_id" field.
func TokenFamilyIDContainsFold(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldContainsFold(FieldTokenFamilyID, v))
}

// DeviceNameEQ applies the EQ predicate on the "device_name" field.
func DeviceNameEQ(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldDeviceName, v))
}

// DeviceNameNEQ applies the NEQ predicate on the "device_name" field.
func DeviceNameNEQ(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNEQ(FieldDeviceName, v))
}

// DeviceNameIn applies the In predicate on the "device_name" field.
func DeviceNameIn(vs ...string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIn(FieldDeviceName, vs...))
}

// DeviceNameNotIn applies the NotIn predicate on the "device_name" field.
func DeviceNameNotIn(vs ...string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotIn(FieldDeviceName, vs...))
}

// DeviceNameGT applies the GT predicate on the "device_name" field.
func DeviceNameGT(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGT(FieldDeviceName, v))
}

// DeviceNameGTE applies the GTE predicate on the "device_name" field.
func DeviceNameGTE(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGTE(FieldDeviceName, v))
}

// DeviceNameLT applies the LT predicate on the "device_name" field.
func DeviceNameLT(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLT(FieldDeviceName, v))
}

// DeviceNameLTE applies the LTE predicate on the "device_name" field.
func DeviceNameLTE(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLTE(FieldDeviceName, v))
}

// DeviceNameContains applies the Contains predicate on the "device_name" field.
func DeviceNameContains(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldContains(FieldDeviceName, v))
}

// DeviceNameHasPrefix applies the HasPrefix predicate on the "device_name" field.
func DeviceNameHasPrefix(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldHasPrefix(FieldDeviceName, v))
}

// DeviceNameHasSuffix applies the HasSuffix predicate on the "device_name" field.
func DeviceNameHasSuffix(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldHasSuffix(FieldDeviceName, v))
}

// DeviceNameEqualFold applies the EqualFold predicate on the "device_name" field.
func DeviceNameEqualFold(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEqualFold(FieldDeviceName, v))
}

// DeviceNameContainsFold applies the ContainsFold predicate on the "device_name" field.
func DeviceNameContainsFold(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldContainsFold(FieldDeviceName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldContainsFold(FieldPlatform, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotIn(FieldStatus, vs...))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotNull(FieldLastUsedAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.FieldNotNull(FieldRevokedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppOAuthSession) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppOAuthSession) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppOAuthSession) predicate.AppOAuthSession {
	return predicate.AppOAuthSession(sql.NotPredicates(p))
}
