// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/appauthorization"
)

// AppAuthorizationCreate is the builder for creating a AppAuthorization entity.
type AppAuthorizationCreate struct {
	config
	mutation *AppAuthorizationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AppAuthorizationCreate) SetCreatedAt(v time.Time) *AppAuthorizationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AppAuthorizationCreate) SetNillableCreatedAt(v *time.Time) *AppAuthorizationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AppAuthorizationCreate) SetUpdatedAt(v time.Time) *AppAuthorizationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AppAuthorizationCreate) SetNillableUpdatedAt(v *time.Time) *AppAuthorizationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AppAuthorizationCreate) SetUserID(v int64) *AppAuthorizationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGrantID sets the "grant_id" field.
func (_c *AppAuthorizationCreate) SetGrantID(v string) *AppAuthorizationCreate {
	_c.mutation.SetGrantID(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *AppAuthorizationCreate) SetClientID(v string) *AppAuthorizationCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *AppAuthorizationCreate) SetDeviceName(v string) *AppAuthorizationCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *AppAuthorizationCreate) SetNillableDeviceName(v *string) *AppAuthorizationCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *AppAuthorizationCreate) SetPlatform(v string) *AppAuthorizationCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *AppAuthorizationCreate) SetNillablePlatform(v *string) *AppAuthorizationCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *AppAuthorizationCreate) SetScopes(v []string) *AppAuthorizationCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetTokenFamilyID sets the "token_family_id" field.
func (_c *AppAuthorizationCreate) SetTokenFamilyID(v string) *AppAuthorizationCreate {
	_c.mutation.SetTokenFamilyID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AppAuthorizationCreate) SetStatus(v string) *AppAuthorizationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AppAuthorizationCreate) SetNillableStatus(v *string) *AppAuthorizationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *AppAuthorizationCreate) SetLastUsedAt(v time.Time) *AppAuthorizationCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *AppAuthorizationCreate) SetNillableLastUsedAt(v *time.Time) *AppAuthorizationCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *AppAuthorizationCreate) SetRevokedAt(v time.Time) *AppAuthorizationCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *AppAuthorizationCreate) SetNillableRevokedAt(v *time.Time) *AppAuthorizationCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// Mutation returns the AppAuthorizationMutation object of the builder.
func (_c *AppAuthorizationCreate) Mutation() *AppAuthorizationMutation {
	return _c.mutation
}

// Save creates the AppAuthorization in the database.
func (_c *AppAuthorizationCreate) Save(ctx context.Context) (*AppAuthorization, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppAuthorizationCreate) SaveX(ctx context.Context) *AppAuthorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppAuthorizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppAuthorizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppAuthorizationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := appauthorization.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := appauthorization.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeviceName(); !ok {
		v := appauthorization.DefaultDeviceName
		_c.mutation.SetDeviceName(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := appauthorization.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		v := appauthorization.DefaultScopes()
		_c.mutation.SetScopes(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := appauthorization.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppAuthorizationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AppAuthorization.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AppAuthorization.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AppAuthorization.user_id"`)}
	}
	if _, ok := _c.mutation.GrantID(); !ok {
		return &ValidationError{Name: "grant_id", err: errors.New(`ent: missing required field "AppAuthorization.grant_id"`)}
	}
	if v, ok := _c.mutation.GrantID(); ok {
		if err := appauthorization.GrantIDValidator(v); err != nil {
			return &ValidationError{Name: "grant_id", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.grant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "AppAuthorization.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := appauthorization.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceName(); !ok {
		return &ValidationError{Name: "device_name", err: errors.New(`ent: missing required field "AppAuthorization.device_name"`)}
	}
	if v, ok := _c.mutation.DeviceName(); ok {
		if err := appauthorization.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.device_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "AppAuthorization.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := appauthorization.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "AppAuthorization.scopes"`)}
	}
	if _, ok := _c.mutation.TokenFamilyID(); !ok {
		return &ValidationError{Name: "token_family_id", err: errors.New(`ent: missing required field "AppAuthorization.token_family_id"`)}
	}
	if v, ok := _c.mutation.TokenFamilyID(); ok {
		if err := appauthorization.TokenFamilyIDValidator(v); err != nil {
			return &ValidationError{Name: "token_family_id", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.token_family_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AppAuthorization.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := appauthorization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.status": %w`, err)}
		}
	}
	return nil
}

func (_c *AppAuthorizationCreate) sqlSave(ctx context.Context) (*AppAuthorization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppAuthorizationCreate) createSpec() (*AppAuthorization, *sqlgraph.CreateSpec) {
	var (
		_node = &AppAuthorization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(appauthorization.Table, sqlgraph.NewFieldSpec(appauthorization.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(appauthorization.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(appauthorization.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(appauthorization.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GrantID(); ok {
		_spec.SetField(appauthorization.FieldGrantID, field.TypeString, value)
		_node.GrantID = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(appauthorization.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(appauthorization.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(appauthorization.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(appauthorization.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.TokenFamilyID(); ok {
		_spec.SetField(appauthorization.FieldTokenFamilyID, field.TypeString, value)
		_node.TokenFamilyID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(appauthorization.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(appauthorization.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(appauthorization.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppAuthorization.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AppAuthorizationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AppAuthorizationCreate) OnConflict(opts ...sql.ConflictOption) *AppAuthorizationUpsertOne {
	_c.conflict = opts
	return &AppAuthorizationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppAuthorization.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AppAuthorizationCreate) OnConflictColumns(columns ...string) *AppAuthorizationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AppAuthorizationUpsertOne{
		create: _c,
	}
}

type (
	// AppAuthorizationUpsertOne is the builder for "upsert"-ing
	//  one AppAuthorization node.
	AppAuthorizationUpsertOne struct {
		create *AppAuthorizationCreate
	}

	// AppAuthorizationUpsert is the "OnConflict" setter.
	AppAuthorizationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AppAuthorizationUpsert) SetUpdatedAt(v time.Time) *AppAuthorizationUpsert {
	u.Set(appauthorization.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppAuthorizationUpsert) UpdateUpdatedAt() *AppAuthorizationUpsert {
	u.SetExcluded(appauthorization.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AppAuthorizationUpsert) SetUserID(v int64) *AppAuthorizationUpsert {
	u.Set(appauthorization.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AppAuthorizationUpsert) UpdateUserID() *AppAuthorizationUpsert {
	u.SetExcluded(appauthorization.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *AppAuthorizationUpsert) AddUserID(v int64) *AppAuthorizationUpsert {
	u.Add(appauthorization.FieldUserID, v)
	return u
}

// SetGrantID sets the "grant_id" field.
func (u *AppAuthorizationUpsert) SetGrantID(v string) *AppAuthorizationUpsert {
	u.Set(appauthorization.FieldGrantID, v)
	return u
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *AppAuthorizationUpsert) UpdateGrantID() *AppAuthorizationUpsert {
	u.SetExcluded(appauthorization.FieldGrantID)
	return u
}

// SetClientID sets the "client_id" field.
func (u *AppAuthorizationUpsert) SetClientID(v string) *AppAuthorizationUpsert {
	u.Set(appauthorization.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AppAuthorizationUpsert) UpdateClientID() *AppAuthorizationUpsert {
	u.SetExcluded(appauthorization.FieldClientID)
	return u
}

// SetDeviceName sets the "device_name" field.
func (u *AppAuthorizationUpsert) SetDeviceName(v string) *AppAuthorizationUpsert {
	u.Set(appauthorization.FieldDeviceName, v)
	return u
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *AppAuthorizationUpsert) UpdateDeviceName() *AppAuthorizationUpsert {
	u.SetExcluded(appauthorization.FieldDeviceName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *AppAuthorizationUpsert) SetPlatform(v string) *AppAuthorizationUpsert {
	u.Set(appauthorization.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AppAuthorizationUpsert) UpdatePlatform() *AppAuthorizationUpsert {
	u.SetExcluded(appauthorization.FieldPlatform)
	return u
}

// SetScopes sets the "scopes" field.
func (u *AppAuthorizationUpsert) SetScopes(v []string) *AppAuthorizationUpsert {
	u.Set(appauthorization.FieldScopes, v)
	return u
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AppAuthorizationUpsert) UpdateScopes() *AppAuthorizationUpsert {
	u.SetExcluded(appauthorization.FieldScopes)
	return u
}

// SetTokenFamilyID sets the "token_family_id" field.
func (u *AppAuthorizationUpsert) SetTokenFamilyID(v string) *AppAuthorizationUpsert {
	u.Set(appauthorization.FieldTokenFamilyID, v)
	return u
}

// UpdateTokenFamilyID sets the "token_family_id" field to the value that was provided on create.
func (u *AppAuthorizationUpsert) UpdateTokenFamilyID() *AppAuthorizationUpsert {
	u.SetExcluded(appauthorization.FieldTokenFamilyID)
	return u
}

// SetStatus sets the "status" field.
func (u *AppAuthorizationUpsert) SetStatus(v string) *AppAuthorizationUpsert {
	u.Set(appauthorization.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AppAuthorizationUpsert) UpdateStatus() *AppAuthorizationUpsert {
	u.SetExcluded(appauthorization.FieldStatus)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *AppAuthorizationUpsert) SetLastUsedAt(v time.Time) *AppAuthorizationUpsert {
	u.Set(appauthorization.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *AppAuthorizationUpsert) UpdateLastUsedAt() *AppAuthorizationUpsert {
	u.SetExcluded(appauthorization.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *AppAuthorizationUpsert) ClearLastUsedAt() *AppAuthorizationUpsert {
	u.SetNull(appauthorization.FieldLastUsedAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AppAuthorizationUpsert) SetRevokedAt(v time.Time) *AppAuthorizationUpsert {
	u.Set(appauthorization.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AppAuthorizationUpsert) UpdateRevokedAt() *AppAuthorizationUpsert {
	u.SetExcluded(appauthorization.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AppAuthorizationUpsert) ClearRevokedAt() *AppAuthorizationUpsert {
	u.SetNull(appauthorization.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AppAuthorization.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AppAuthorizationUpsertOne) UpdateNewValues() *AppAuthorizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(appauthorization.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AppAuthorization.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AppAuthorizationUpsertOne) Ignore() *AppAuthorizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppAuthorizationUpsertOne) DoNothing() *AppAuthorizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppAuthorizationCreate.OnConflict
// documentation for more info.
func (u *AppAuthorizationUpsertOne) Update(set func(*AppAuthorizationUpsert)) *AppAuthorizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppAuthorizationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppAuthorizationUpsertOne) SetUpdatedAt(v time.Time) *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppAuthorizationUpsertOne) UpdateUpdatedAt() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *AppAuthorizationUpsertOne) SetUserID(v int64) *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AppAuthorizationUpsertOne) AddUserID(v int64) *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AppAuthorizationUpsertOne) UpdateUserID() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateUserID()
	})
}

// SetGrantID sets the "grant_id" field.
func (u *AppAuthorizationUpsertOne) SetGrantID(v string) *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *AppAuthorizationUpsertOne) UpdateGrantID() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateGrantID()
	})
}

// SetClientID sets the "client_id" field.
func (u *AppAuthorizationUpsertOne) SetClientID(v string) *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AppAuthorizationUpsertOne) UpdateClientID() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateClientID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *AppAuthorizationUpsertOne) SetDeviceName(v string) *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *AppAuthorizationUpsertOne) UpdateDeviceName() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateDeviceName()
	})
}

// SetPlatform sets the "platform" field.
func (u *AppAuthorizationUpsertOne) SetPlatform(v string) *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AppAuthorizationUpsertOne) UpdatePlatform() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdatePlatform()
	})
}

// SetScopes sets the "scopes" field.
func (u *AppAuthorizationUpsertOne) SetScopes(v []string) *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AppAuthorizationUpsertOne) UpdateScopes() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateScopes()
	})
}

// SetTokenFamilyID sets the "token_family_id" field.
func (u *AppAuthorizationUpsertOne) SetTokenFamilyID(v string) *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetTokenFamilyID(v)
	})
}

// UpdateTokenFamilyID sets the "token_family_id" field to the value that was provided on create.
func (u *AppAuthorizationUpsertOne) UpdateTokenFamilyID() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateTokenFamilyID()
	})
}

// SetStatus sets the "status" field.
func (u *AppAuthorizationUpsertOne) SetStatus(v string) *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AppAuthorizationUpsertOne) UpdateStatus() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateStatus()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *AppAuthorizationUpsertOne) SetLastUsedAt(v time.Time) *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *AppAuthorizationUpsertOne) UpdateLastUsedAt() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *AppAuthorizationUpsertOne) ClearLastUsedAt() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AppAuthorizationUpsertOne) SetRevokedAt(v time.Time) *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AppAuthorizationUpsertOne) UpdateRevokedAt() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AppAuthorizationUpsertOne) ClearRevokedAt() *AppAuthorizationUpsertOne {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *AppAuthorizationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppAuthorizationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppAuthorizationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AppAuthorizationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AppAuthorizationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AppAuthorizationCreateBulk is the builder for creating many AppAuthorization entities in bulk.
type AppAuthorizationCreateBulk struct {
	config
	err      error
	builders []*AppAuthorizationCreate
	conflict []sql.ConflictOption
}

// Save creates the AppAuthorization entities in the database.
func (_c *AppAuthorizationCreateBulk) Save(ctx context.Context) ([]*AppAuthorization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AppAuthorization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppAuthorizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppAuthorizationCreateBulk) SaveX(ctx context.Context) []*AppAuthorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppAuthorizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppAuthorizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppAuthorization.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AppAuthorizationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AppAuthorizationCreateBulk) OnConflict(opts ...sql.ConflictOption) *AppAuthorizationUpsertBulk {
	_c.conflict = opts
	return &AppAuthorizationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppAuthorization.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AppAuthorizationCreateBulk) OnConflictColumns(columns ...string) *AppAuthorizationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AppAuthorizationUpsertBulk{
		create: _c,
	}
}

// AppAuthorizationUpsertBulk is the builder for "upsert"-ing
// a bulk of AppAuthorization nodes.
type AppAuthorizationUpsertBulk struct {
	create *AppAuthorizationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AppAuthorization.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AppAuthorizationUpsertBulk) UpdateNewValues() *AppAuthorizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(appauthorization.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AppAuthorization.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AppAuthorizationUpsertBulk) Ignore() *AppAuthorizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppAuthorizationUpsertBulk) DoNothing() *AppAuthorizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppAuthorizationCreateBulk.OnConflict
// documentation for more info.
func (u *AppAuthorizationUpsertBulk) Update(set func(*AppAuthorizationUpsert)) *AppAuthorizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppAuthorizationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppAuthorizationUpsertBulk) SetUpdatedAt(v time.Time) *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppAuthorizationUpsertBulk) UpdateUpdatedAt() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *AppAuthorizationUpsertBulk) SetUserID(v int64) *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AppAuthorizationUpsertBulk) AddUserID(v int64) *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AppAuthorizationUpsertBulk) UpdateUserID() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateUserID()
	})
}

// SetGrantID sets the "grant_id" field.
func (u *AppAuthorizationUpsertBulk) SetGrantID(v string) *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *AppAuthorizationUpsertBulk) UpdateGrantID() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateGrantID()
	})
}

// SetClientID sets the "client_id" field.
func (u *AppAuthorizationUpsertBulk) SetClientID(v string) *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AppAuthorizationUpsertBulk) UpdateClientID() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateClientID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *AppAuthorizationUpsertBulk) SetDeviceName(v string) *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *AppAuthorizationUpsertBulk) UpdateDeviceName() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateDeviceName()
	})
}

// SetPlatform sets the "platform" field.
func (u *AppAuthorizationUpsertBulk) SetPlatform(v string) *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AppAuthorizationUpsertBulk) UpdatePlatform() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdatePlatform()
	})
}

// SetScopes sets the "scopes" field.
func (u *AppAuthorizationUpsertBulk) SetScopes(v []string) *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AppAuthorizationUpsertBulk) UpdateScopes() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateScopes()
	})
}

// SetTokenFamilyID sets the "token_family_id" field.
func (u *AppAuthorizationUpsertBulk) SetTokenFamilyID(v string) *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetTokenFamilyID(v)
	})
}

// UpdateTokenFamilyID sets the "token_family_id" field to the value that was provided on create.
func (u *AppAuthorizationUpsertBulk) UpdateTokenFamilyID() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateTokenFamilyID()
	})
}

// SetStatus sets the "status" field.
func (u *AppAuthorizationUpsertBulk) SetStatus(v string) *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AppAuthorizationUpsertBulk) UpdateStatus() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateStatus()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *AppAuthorizationUpsertBulk) SetLastUsedAt(v time.Time) *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *AppAuthorizationUpsertBulk) UpdateLastUsedAt() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *AppAuthorizationUpsertBulk) ClearLastUsedAt() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AppAuthorizationUpsertBulk) SetRevokedAt(v time.Time) *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AppAuthorizationUpsertBulk) UpdateRevokedAt() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AppAuthorizationUpsertBulk) ClearRevokedAt() *AppAuthorizationUpsertBulk {
	return u.Update(func(s *AppAuthorizationUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *AppAuthorizationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AppAuthorizationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppAuthorizationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppAuthorizationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
