// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/appauthorization"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AppAuthorizationUpdate is the builder for updating AppAuthorization entities.
type AppAuthorizationUpdate struct {
	config
	hooks    []Hook
	mutation *AppAuthorizationMutation
}

// Where appends a list predicates to the AppAuthorizationUpdate builder.
func (_u *AppAuthorizationUpdate) Where(ps ...predicate.AppAuthorization) *AppAuthorizationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppAuthorizationUpdate) SetUpdatedAt(v time.Time) *AppAuthorizationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AppAuthorizationUpdate) SetUserID(v int64) *AppAuthorizationUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AppAuthorizationUpdate) SetNillableUserID(v *int64) *AppAuthorizationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AppAuthorizationUpdate) AddUserID(v int64) *AppAuthorizationUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGrantID sets the "grant_id" field.
func (_u *AppAuthorizationUpdate) SetGrantID(v string) *AppAuthorizationUpdate {
	_u.mutation.SetGrantID(v)
	return _u
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (_u *AppAuthorizationUpdate) SetNillableGrantID(v *string) *AppAuthorizationUpdate {
	if v != nil {
		_u.SetGrantID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AppAuthorizationUpdate) SetClientID(v string) *AppAuthorizationUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AppAuthorizationUpdate) SetNillableClientID(v *string) *AppAuthorizationUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *AppAuthorizationUpdate) SetDeviceName(v string) *AppAuthorizationUpdate {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *AppAuthorizationUpdate) SetNillableDeviceName(v *string) *AppAuthorizationUpdate {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AppAuthorizationUpdate) SetPlatform(v string) *AppAuthorizationUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AppAuthorizationUpdate) SetNillablePlatform(v *string) *AppAuthorizationUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AppAuthorizationUpdate) SetScopes(v []string) *AppAuthorizationUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AppAuthorizationUpdate) AppendScopes(v []string) *AppAuthorizationUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetTokenFamilyID sets the "token_family_id" field.
func (_u *AppAuthorizationUpdate) SetTokenFamilyID(v string) *AppAuthorizationUpdate {
	_u.mutation.SetTokenFamilyID(v)
	return _u
}

// SetNillableTokenFamilyID sets the "token_family_id" field if the given value is not nil.
func (_u *AppAuthorizationUpdate) SetNillableTokenFamilyID(v *string) *AppAuthorizationUpdate {
	if v != nil {
		_u.SetTokenFamilyID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AppAuthorizationUpdate) SetStatus(v string) *AppAuthorizationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AppAuthorizationUpdate) SetNillableStatus(v *string) *AppAuthorizationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AppAuthorizationUpdate) SetLastUsedAt(v time.Time) *AppAuthorizationUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AppAuthorizationUpdate) SetNillableLastUsedAt(v *time.Time) *AppAuthorizationUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AppAuthorizationUpdate) ClearLastUsedAt() *AppAuthorizationUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AppAuthorizationUpdate) SetRevokedAt(v time.Time) *AppAuthorizationUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AppAuthorizationUpdate) SetNillableRevokedAt(v *time.Time) *AppAuthorizationUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AppAuthorizationUpdate) ClearRevokedAt() *AppAuthorizationUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the AppAuthorizationMutation object of the builder.
func (_u *AppAuthorizationUpdate) Mutation() *AppAuthorizationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppAuthorizationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppAuthorizationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppAuthorizationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppAuthorizationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppAuthorizationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := appauthorization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppAuthorizationUpdate) check() error {
	if v, ok := _u.mutation.GrantID(); ok {
		if err := appauthorization.GrantIDValidator(v); err != nil {
			return &ValidationError{Name: "grant_id", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.grant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := appauthorization.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceName(); ok {
		if err := appauthorization.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.device_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := appauthorization.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenFamilyID(); ok {
		if err := appauthorization.TokenFamilyIDValidator(v); err != nil {
			return &ValidationError{Name: "token_family_id", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.token_family_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := appauthorization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AppAuthorizationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(appauthorization.Table, appauthorization.Columns, sqlgraph.NewFieldSpec(appauthorization.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(appauthorization.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(appauthorization.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(appauthorization.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GrantID(); ok {
		_spec.SetField(appauthorization.FieldGrantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(appauthorization.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(appauthorization.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(appauthorization.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(appauthorization.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, appauthorization.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.TokenFamilyID(); ok {
		_spec.SetField(appauthorization.FieldTokenFamilyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(appauthorization.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(appauthorization.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(appauthorization.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(appauthorization.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(appauthorization.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appauthorization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppAuthorizationUpdateOne is the builder for updating a single AppAuthorization entity.
type AppAuthorizationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppAuthorizationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppAuthorizationUpdateOne) SetUpdatedAt(v time.Time) *AppAuthorizationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AppAuthorizationUpdateOne) SetUserID(v int64) *AppAuthorizationUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AppAuthorizationUpdateOne) SetNillableUserID(v *int64) *AppAuthorizationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AppAuthorizationUpdateOne) AddUserID(v int64) *AppAuthorizationUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGrantID sets the "grant_id" field.
func (_u *AppAuthorizationUpdateOne) SetGrantID(v string) *AppAuthorizationUpdateOne {
	_u.mutation.SetGrantID(v)
	return _u
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (_u *AppAuthorizationUpdateOne) SetNillableGrantID(v *string) *AppAuthorizationUpdateOne {
	if v != nil {
		_u.SetGrantID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AppAuthorizationUpdateOne) SetClientID(v string) *AppAuthorizationUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AppAuthorizationUpdateOne) SetNillableClientID(v *string) *AppAuthorizationUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *AppAuthorizationUpdateOne) SetDeviceName(v string) *AppAuthorizationUpdateOne {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *AppAuthorizationUpdateOne) SetNillableDeviceName(v *string) *AppAuthorizationUpdateOne {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AppAuthorizationUpdateOne) SetPlatform(v string) *AppAuthorizationUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AppAuthorizationUpdateOne) SetNillablePlatform(v *string) *AppAuthorizationUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AppAuthorizationUpdateOne) SetScopes(v []string) *AppAuthorizationUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AppAuthorizationUpdateOne) AppendScopes(v []string) *AppAuthorizationUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetTokenFamilyID sets the "token_family_id" field.
func (_u *AppAuthorizationUpdateOne) SetTokenFamilyID(v string) *AppAuthorizationUpdateOne {
	_u.mutation.SetTokenFamilyID(v)
	return _u
}

// SetNillableTokenFamilyID sets the "token_family_id" field if the given value is not nil.
func (_u *AppAuthorizationUpdateOne) SetNillableTokenFamilyID(v *string) *AppAuthorizationUpdateOne {
	if v != nil {
		_u.SetTokenFamilyID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AppAuthorizationUpdateOne) SetStatus(v string) *AppAuthorizationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AppAuthorizationUpdateOne) SetNillableStatus(v *string) *AppAuthorizationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AppAuthorizationUpdateOne) SetLastUsedAt(v time.Time) *AppAuthorizationUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AppAuthorizationUpdateOne) SetNillableLastUsedAt(v *time.Time) *AppAuthorizationUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AppAuthorizationUpdateOne) ClearLastUsedAt() *AppAuthorizationUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AppAuthorizationUpdateOne) SetRevokedAt(v time.Time) *AppAuthorizationUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AppAuthorizationUpdateOne) SetNillableRevokedAt(v *time.Time) *AppAuthorizationUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AppAuthorizationUpdateOne) ClearRevokedAt() *AppAuthorizationUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the AppAuthorizationMutation object of the builder.
func (_u *AppAuthorizationUpdateOne) Mutation() *AppAuthorizationMutation {
	return _u.mutation
}

// Where appends a list predicates to the AppAuthorizationUpdate builder.
func (_u *AppAuthorizationUpdateOne) Where(ps ...predicate.AppAuthorization) *AppAuthorizationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppAuthorizationUpdateOne) Select(field string, fields ...string) *AppAuthorizationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AppAuthorization entity.
func (_u *AppAuthorizationUpdateOne) Save(ctx context.Context) (*AppAuthorization, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppAuthorizationUpdateOne) SaveX(ctx context.Context) *AppAuthorization {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppAuthorizationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppAuthorizationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppAuthorizationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := appauthorization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppAuthorizationUpdateOne) check() error {
	if v, ok := _u.mutation.GrantID(); ok {
		if err := appauthorization.GrantIDValidator(v); err != nil {
			return &ValidationError{Name: "grant_id", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.grant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := appauthorization.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceName(); ok {
		if err := appauthorization.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.device_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := appauthorization.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenFamilyID(); ok {
		if err := appauthorization.TokenFamilyIDValidator(v); err != nil {
			return &ValidationError{Name: "token_family_id", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.token_family_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := appauthorization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AppAuthorization.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AppAuthorizationUpdateOne) sqlSave(ctx context.Context) (_node *AppAuthorization, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(appauthorization.Table, appauthorization.Columns, sqlgraph.NewFieldSpec(appauthorization.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppAuthorization.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appauthorization.FieldID)
		for _, f := range fields {
			if !appauthorization.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appauthorization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(appauthorization.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(appauthorization.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(appauthorization.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GrantID(); ok {
		_spec.SetField(appauthorization.FieldGrantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(appauthorization.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(appauthorization.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(appauthorization.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(appauthorization.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, appauthorization.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.TokenFamilyID(); ok {
		_spec.SetField(appauthorization.FieldTokenFamilyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(appauthorization.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(appauthorization.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(appauthorization.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(appauthorization.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(appauthorization.FieldRevokedAt, field.TypeTime)
	}
	_node = &AppAuthorization{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appauthorization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
