// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/appoauthsession"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AppOAuthSessionDelete is the builder for deleting a AppOAuthSession entity.
type AppOAuthSessionDelete struct {
	config
	hooks    []Hook
	mutation *AppOAuthSessionMutation
}

// Where appends a list predicates to the AppOAuthSessionDelete builder.
func (_d *AppOAuthSessionDelete) Where(ps ...predicate.AppOAuthSession) *AppOAuthSessionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AppOAuthSessionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AppOAuthSessionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AppOAuthSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(appoauthsession.Table, sqlgraph.NewFieldSpec(appoauthsession.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AppOAuthSessionDeleteOne is the builder for deleting a single AppOAuthSession entity.
type AppOAuthSessionDeleteOne struct {
	_d *AppOAuthSessionDelete
}

// Where appends a list predicates to the AppOAuthSessionDelete builder.
func (_d *AppOAuthSessionDeleteOne) Where(ps ...predicate.AppOAuthSession) *AppOAuthSessionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AppOAuthSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{appoauthsession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AppOAuthSessionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
