// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/appoauthsession"
)

// AppOAuthSessionCreate is the builder for creating a AppOAuthSession entity.
type AppOAuthSessionCreate struct {
	config
	mutation *AppOAuthSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AppOAuthSessionCreate) SetCreatedAt(v time.Time) *AppOAuthSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AppOAuthSessionCreate) SetNillableCreatedAt(v *time.Time) *AppOAuthSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AppOAuthSessionCreate) SetUpdatedAt(v time.Time) *AppOAuthSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AppOAuthSessionCreate) SetNillableUpdatedAt(v *time.Time) *AppOAuthSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAppGrantID sets the "app_grant_id" field.
func (_c *AppOAuthSessionCreate) SetAppGrantID(v int64) *AppOAuthSessionCreate {
	_c.mutation.SetAppGrantID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *AppOAuthSessionCreate) SetSessionID(v string) *AppOAuthSessionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetInstallationIDHash sets the "installation_id_hash" field.
func (_c *AppOAuthSessionCreate) SetInstallationIDHash(v string) *AppOAuthSessionCreate {
	_c.mutation.SetInstallationIDHash(v)
	return _c
}

// SetTokenFamilyID sets the "token_family_id" field.
func (_c *AppOAuthSessionCreate) SetTokenFamilyID(v string) *AppOAuthSessionCreate {
	_c.mutation.SetTokenFamilyID(v)
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *AppOAuthSessionCreate) SetDeviceName(v string) *AppOAuthSessionCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *AppOAuthSessionCreate) SetNillableDeviceName(v *string) *AppOAuthSessionCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *AppOAuthSessionCreate) SetPlatform(v string) *AppOAuthSessionCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *AppOAuthSessionCreate) SetNillablePlatform(v *string) *AppOAuthSessionCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *AppOAuthSessionCreate) SetScopes(v []string) *AppOAuthSessionCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AppOAuthSessionCreate) SetStatus(v appoauthsession.Status) *AppOAuthSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AppOAuthSessionCreate) SetNillableStatus(v *appoauthsession.Status) *AppOAuthSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *AppOAuthSessionCreate) SetLastUsedAt(v time.Time) *AppOAuthSessionCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *AppOAuthSessionCreate) SetNillableLastUsedAt(v *time.Time) *AppOAuthSessionCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *AppOAuthSessionCreate) SetRevokedAt(v time.Time) *AppOAuthSessionCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *AppOAuthSessionCreate) SetNillableRevokedAt(v *time.Time) *AppOAuthSessionCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// Mutation returns the AppOAuthSessionMutation object of the builder.
func (_c *AppOAuthSessionCreate) Mutation() *AppOAuthSessionMutation {
	return _c.mutation
}

// Save creates the AppOAuthSession in the database.
func (_c *AppOAuthSessionCreate) Save(ctx context.Context) (*AppOAuthSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppOAuthSessionCreate) SaveX(ctx context.Context) *AppOAuthSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppOAuthSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppOAuthSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppOAuthSessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := appoauthsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := appoauthsession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeviceName(); !ok {
		v := appoauthsession.DefaultDeviceName
		_c.mutation.SetDeviceName(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := appoauthsession.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		v := appoauthsession.DefaultScopes()
		_c.mutation.SetScopes(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := appoauthsession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppOAuthSessionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AppOAuthSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AppOAuthSession.updated_at"`)}
	}
	if _, ok := _c.mutation.AppGrantID(); !ok {
		return &ValidationError{Name: "app_grant_id", err: errors.New(`ent: missing required field "AppOAuthSession.app_grant_id"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "AppOAuthSession.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := appoauthsession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InstallationIDHash(); !ok {
		return &ValidationError{Name: "installation_id_hash", err: errors.New(`ent: missing required field "AppOAuthSession.installation_id_hash"`)}
	}
	if v, ok := _c.mutation.InstallationIDHash(); ok {
		if err := appoauthsession.InstallationIDHashValidator(v); err != nil {
			return &ValidationError{Name: "installation_id_hash", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.installation_id_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenFamilyID(); !ok {
		return &ValidationError{Name: "token_family_id", err: errors.New(`ent: missing required field "AppOAuthSession.token_family_id"`)}
	}
	if v, ok := _c.mutation.TokenFamilyID(); ok {
		if err := appoauthsession.TokenFamilyIDValidator(v); err != nil {
			return &ValidationError{Name: "token_family_id", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.token_family_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceName(); !ok {
		return &ValidationError{Name: "device_name", err: errors.New(`ent: missing required field "AppOAuthSession.device_name"`)}
	}
	if v, ok := _c.mutation.DeviceName(); ok {
		if err := appoauthsession.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.device_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "AppOAuthSession.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := appoauthsession.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "AppOAuthSession.scopes"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AppOAuthSession.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := appoauthsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.status": %w`, err)}
		}
	}
	return nil
}

func (_c *AppOAuthSessionCreate) sqlSave(ctx context.Context) (*AppOAuthSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppOAuthSessionCreate) createSpec() (*AppOAuthSession, *sqlgraph.CreateSpec) {
	var (
		_node = &AppOAuthSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(appoauthsession.Table, sqlgraph.NewFieldSpec(appoauthsession.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(appoauthsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(appoauthsession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AppGrantID(); ok {
		_spec.SetField(appoauthsession.FieldAppGrantID, field.TypeInt64, value)
		_node.AppGrantID = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(appoauthsession.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.InstallationIDHash(); ok {
		_spec.SetField(appoauthsession.FieldInstallationIDHash, field.TypeString, value)
		_node.InstallationIDHash = value
	}
	if value, ok := _c.mutation.TokenFamilyID(); ok {
		_spec.SetField(appoauthsession.FieldTokenFamilyID, field.TypeString, value)
		_node.TokenFamilyID = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(appoauthsession.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(appoauthsession.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(appoauthsession.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(appoauthsession.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(appoauthsession.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(appoauthsession.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppOAuthSession.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AppOAuthSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AppOAuthSessionCreate) OnConflict(opts ...sql.ConflictOption) *AppOAuthSessionUpsertOne {
	_c.conflict = opts
	return &AppOAuthSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppOAuthSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AppOAuthSessionCreate) OnConflictColumns(columns ...string) *AppOAuthSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AppOAuthSessionUpsertOne{
		create: _c,
	}
}

type (
	// AppOAuthSessionUpsertOne is the builder for "upsert"-ing
	//  one AppOAuthSession node.
	AppOAuthSessionUpsertOne struct {
		create *AppOAuthSessionCreate
	}

	// AppOAuthSessionUpsert is the "OnConflict" setter.
	AppOAuthSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AppOAuthSessionUpsert) SetUpdatedAt(v time.Time) *AppOAuthSessionUpsert {
	u.Set(appoauthsession.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppOAuthSessionUpsert) UpdateUpdatedAt() *AppOAuthSessionUpsert {
	u.SetExcluded(appoauthsession.FieldUpdatedAt)
	return u
}

// SetAppGrantID sets the "app_grant_id" field.
func (u *AppOAuthSessionUpsert) SetAppGrantID(v int64) *AppOAuthSessionUpsert {
	u.Set(appoauthsession.FieldAppGrantID, v)
	return u
}

// UpdateAppGrantID sets the "app_grant_id" field to the value that was provided on create.
func (u *AppOAuthSessionUpsert) UpdateAppGrantID() *AppOAuthSessionUpsert {
	u.SetExcluded(appoauthsession.FieldAppGrantID)
	return u
}

// AddAppGrantID adds v to the "app_grant_id" field.
func (u *AppOAuthSessionUpsert) AddAppGrantID(v int64) *AppOAuthSessionUpsert {
	u.Add(appoauthsession.FieldAppGrantID, v)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *AppOAuthSessionUpsert) SetSessionID(v string) *AppOAuthSessionUpsert {
	u.Set(appoauthsession.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AppOAuthSessionUpsert) UpdateSessionID() *AppOAuthSessionUpsert {
	u.SetExcluded(appoauthsession.FieldSessionID)
	return u
}

// SetInstallationIDHash sets the "installation_id_hash" field.
func (u *AppOAuthSessionUpsert) SetInstallationIDHash(v string) *AppOAuthSessionUpsert {
	u.Set(appoauthsession.FieldInstallationIDHash, v)
	return u
}

// UpdateInstallationIDHash sets the "installation_id_hash" field to the value that was provided on create.
func (u *AppOAuthSessionUpsert) UpdateInstallationIDHash() *AppOAuthSessionUpsert {
	u.SetExcluded(appoauthsession.FieldInstallationIDHash)
	return u
}

// SetTokenFamilyID sets the "token_family_id" field.
func (u *AppOAuthSessionUpsert) SetTokenFamilyID(v string) *AppOAuthSessionUpsert {
	u.Set(appoauthsession.FieldTokenFamilyID, v)
	return u
}

// UpdateTokenFamilyID sets the "token_family_id" field to the value that was provided on create.
func (u *AppOAuthSessionUpsert) UpdateTokenFamilyID() *AppOAuthSessionUpsert {
	u.SetExcluded(appoauthsession.FieldTokenFamilyID)
	return u
}

// SetDeviceName sets the "device_name" field.
func (u *AppOAuthSessionUpsert) SetDeviceName(v string) *AppOAuthSessionUpsert {
	u.Set(appoauthsession.FieldDeviceName, v)
	return u
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *AppOAuthSessionUpsert) UpdateDeviceName() *AppOAuthSessionUpsert {
	u.SetExcluded(appoauthsession.FieldDeviceName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *AppOAuthSessionUpsert) SetPlatform(v string) *AppOAuthSessionUpsert {
	u.Set(appoauthsession.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AppOAuthSessionUpsert) UpdatePlatform() *AppOAuthSessionUpsert {
	u.SetExcluded(appoauthsession.FieldPlatform)
	return u
}

// SetScopes sets the "scopes" field.
func (u *AppOAuthSessionUpsert) SetScopes(v []string) *AppOAuthSessionUpsert {
	u.Set(appoauthsession.FieldScopes, v)
	return u
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AppOAuthSessionUpsert) UpdateScopes() *AppOAuthSessionUpsert {
	u.SetExcluded(appoauthsession.FieldScopes)
	return u
}

// SetStatus sets the "status" field.
func (u *AppOAuthSessionUpsert) SetStatus(v appoauthsession.Status) *AppOAuthSessionUpsert {
	u.Set(appoauthsession.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AppOAuthSessionUpsert) UpdateStatus() *AppOAuthSessionUpsert {
	u.SetExcluded(appoauthsession.FieldStatus)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *AppOAuthSessionUpsert) SetLastUsedAt(v time.Time) *AppOAuthSessionUpsert {
	u.Set(appoauthsession.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *AppOAuthSessionUpsert) UpdateLastUsedAt() *AppOAuthSessionUpsert {
	u.SetExcluded(appoauthsession.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *AppOAuthSessionUpsert) ClearLastUsedAt() *AppOAuthSessionUpsert {
	u.SetNull(appoauthsession.FieldLastUsedAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AppOAuthSessionUpsert) SetRevokedAt(v time.Time) *AppOAuthSessionUpsert {
	u.Set(appoauthsession.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AppOAuthSessionUpsert) UpdateRevokedAt() *AppOAuthSessionUpsert {
	u.SetExcluded(appoauthsession.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AppOAuthSessionUpsert) ClearRevokedAt() *AppOAuthSessionUpsert {
	u.SetNull(appoauthsession.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AppOAuthSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AppOAuthSessionUpsertOne) UpdateNewValues() *AppOAuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(appoauthsession.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AppOAuthSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AppOAuthSessionUpsertOne) Ignore() *AppOAuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppOAuthSessionUpsertOne) DoNothing() *AppOAuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppOAuthSessionCreate.OnConflict
// documentation for more info.
func (u *AppOAuthSessionUpsertOne) Update(set func(*AppOAuthSessionUpsert)) *AppOAuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppOAuthSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppOAuthSessionUpsertOne) SetUpdatedAt(v time.Time) *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertOne) UpdateUpdatedAt() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAppGrantID sets the "app_grant_id" field.
func (u *AppOAuthSessionUpsertOne) SetAppGrantID(v int64) *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetAppGrantID(v)
	})
}

// AddAppGrantID adds v to the "app_grant_id" field.
func (u *AppOAuthSessionUpsertOne) AddAppGrantID(v int64) *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.AddAppGrantID(v)
	})
}

// UpdateAppGrantID sets the "app_grant_id" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertOne) UpdateAppGrantID() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateAppGrantID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *AppOAuthSessionUpsertOne) SetSessionID(v string) *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertOne) UpdateSessionID() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateSessionID()
	})
}

// SetInstallationIDHash sets the "installation_id_hash" field.
func (u *AppOAuthSessionUpsertOne) SetInstallationIDHash(v string) *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetInstallationIDHash(v)
	})
}

// UpdateInstallationIDHash sets the "installation_id_hash" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertOne) UpdateInstallationIDHash() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateInstallationIDHash()
	})
}

// SetTokenFamilyID sets the "token_family_id" field.
func (u *AppOAuthSessionUpsertOne) SetTokenFamilyID(v string) *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetTokenFamilyID(v)
	})
}

// UpdateTokenFamilyID sets the "token_family_id" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertOne) UpdateTokenFamilyID() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateTokenFamilyID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *AppOAuthSessionUpsertOne) SetDeviceName(v string) *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertOne) UpdateDeviceName() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateDeviceName()
	})
}

// SetPlatform sets the "platform" field.
func (u *AppOAuthSessionUpsertOne) SetPlatform(v string) *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertOne) UpdatePlatform() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdatePlatform()
	})
}

// SetScopes sets the "scopes" field.
func (u *AppOAuthSessionUpsertOne) SetScopes(v []string) *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertOne) UpdateScopes() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateScopes()
	})
}

// SetStatus sets the "status" field.
func (u *AppOAuthSessionUpsertOne) SetStatus(v appoauthsession.Status) *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertOne) UpdateStatus() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *AppOAuthSessionUpsertOne) SetLastUsedAt(v time.Time) *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertOne) UpdateLastUsedAt() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *AppOAuthSessionUpsertOne) ClearLastUsedAt() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AppOAuthSessionUpsertOne) SetRevokedAt(v time.Time) *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertOne) UpdateRevokedAt() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AppOAuthSessionUpsertOne) ClearRevokedAt() *AppOAuthSessionUpsertOne {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *AppOAuthSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppOAuthSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppOAuthSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AppOAuthSessionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AppOAuthSessionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AppOAuthSessionCreateBulk is the builder for creating many AppOAuthSession entities in bulk.
type AppOAuthSessionCreateBulk struct {
	config
	err      error
	builders []*AppOAuthSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the AppOAuthSession entities in the database.
func (_c *AppOAuthSessionCreateBulk) Save(ctx context.Context) ([]*AppOAuthSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AppOAuthSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppOAuthSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppOAuthSessionCreateBulk) SaveX(ctx context.Context) []*AppOAuthSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppOAuthSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppOAuthSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppOAuthSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AppOAuthSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AppOAuthSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *AppOAuthSessionUpsertBulk {
	_c.conflict = opts
	return &AppOAuthSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppOAuthSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AppOAuthSessionCreateBulk) OnConflictColumns(columns ...string) *AppOAuthSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AppOAuthSessionUpsertBulk{
		create: _c,
	}
}

// AppOAuthSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of AppOAuthSession nodes.
type AppOAuthSessionUpsertBulk struct {
	create *AppOAuthSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AppOAuthSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AppOAuthSessionUpsertBulk) UpdateNewValues() *AppOAuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(appoauthsession.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AppOAuthSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AppOAuthSessionUpsertBulk) Ignore() *AppOAuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppOAuthSessionUpsertBulk) DoNothing() *AppOAuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppOAuthSessionCreateBulk.OnConflict
// documentation for more info.
func (u *AppOAuthSessionUpsertBulk) Update(set func(*AppOAuthSessionUpsert)) *AppOAuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppOAuthSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppOAuthSessionUpsertBulk) SetUpdatedAt(v time.Time) *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertBulk) UpdateUpdatedAt() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAppGrantID sets the "app_grant_id" field.
func (u *AppOAuthSessionUpsertBulk) SetAppGrantID(v int64) *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetAppGrantID(v)
	})
}

// AddAppGrantID adds v to the "app_grant_id" field.
func (u *AppOAuthSessionUpsertBulk) AddAppGrantID(v int64) *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.AddAppGrantID(v)
	})
}

// UpdateAppGrantID sets the "app_grant_id" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertBulk) UpdateAppGrantID() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateAppGrantID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *AppOAuthSessionUpsertBulk) SetSessionID(v string) *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertBulk) UpdateSessionID() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateSessionID()
	})
}

// SetInstallationIDHash sets the "installation_id_hash" field.
func (u *AppOAuthSessionUpsertBulk) SetInstallationIDHash(v string) *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetInstallationIDHash(v)
	})
}

// UpdateInstallationIDHash sets the "installation_id_hash" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertBulk) UpdateInstallationIDHash() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateInstallationIDHash()
	})
}

// SetTokenFamilyID sets the "token_family_id" field.
func (u *AppOAuthSessionUpsertBulk) SetTokenFamilyID(v string) *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetTokenFamilyID(v)
	})
}

// UpdateTokenFamilyID sets the "token_family_id" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertBulk) UpdateTokenFamilyID() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateTokenFamilyID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *AppOAuthSessionUpsertBulk) SetDeviceName(v string) *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertBulk) UpdateDeviceName() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateDeviceName()
	})
}

// SetPlatform sets the "platform" field.
func (u *AppOAuthSessionUpsertBulk) SetPlatform(v string) *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertBulk) UpdatePlatform() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdatePlatform()
	})
}

// SetScopes sets the "scopes" field.
func (u *AppOAuthSessionUpsertBulk) SetScopes(v []string) *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertBulk) UpdateScopes() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateScopes()
	})
}

// SetStatus sets the "status" field.
func (u *AppOAuthSessionUpsertBulk) SetStatus(v appoauthsession.Status) *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertBulk) UpdateStatus() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *AppOAuthSessionUpsertBulk) SetLastUsedAt(v time.Time) *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertBulk) UpdateLastUsedAt() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *AppOAuthSessionUpsertBulk) ClearLastUsedAt() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AppOAuthSessionUpsertBulk) SetRevokedAt(v time.Time) *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AppOAuthSessionUpsertBulk) UpdateRevokedAt() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AppOAuthSessionUpsertBulk) ClearRevokedAt() *AppOAuthSessionUpsertBulk {
	return u.Update(func(s *AppOAuthSessionUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *AppOAuthSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AppOAuthSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppOAuthSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppOAuthSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
