// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/appoauthgrant"
)

// AppOAuthGrant is the model entity for the AppOAuthGrant schema.
type AppOAuthGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GrantID holds the value of the "grant_id" field.
	GrantID string `json:"grant_id,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// Scopes holds the value of the "scopes" field.
	Scopes []string `json:"scopes,omitempty"`
	// Status holds the value of the "status" field.
	Status appoauthgrant.Status `json:"status,omitempty"`
	// GrantVersion holds the value of the "grant_version" field.
	GrantVersion int `json:"grant_version,omitempty"`
	// FirstAuthorizedAt holds the value of the "first_authorized_at" field.
	FirstAuthorizedAt time.Time `json:"first_authorized_at,omitempty"`
	// LastAuthorizedAt holds the value of the "last_authorized_at" field.
	LastAuthorizedAt time.Time `json:"last_authorized_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt    *time.Time `json:"revoked_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppOAuthGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case appoauthgrant.FieldScopes:
			values[i] = new([]byte)
		case appoauthgrant.FieldID, appoauthgrant.FieldUserID, appoauthgrant.FieldGrantVersion:
			values[i] = new(sql.NullInt64)
		case appoauthgrant.FieldGrantID, appoauthgrant.FieldClientID, appoauthgrant.FieldStatus:
			values[i] = new(sql.NullString)
		case appoauthgrant.FieldCreatedAt, appoauthgrant.FieldUpdatedAt, appoauthgrant.FieldFirstAuthorizedAt, appoauthgrant.FieldLastAuthorizedAt, appoauthgrant.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppOAuthGrant fields.
func (_m *AppOAuthGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appoauthgrant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case appoauthgrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case appoauthgrant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case appoauthgrant.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case appoauthgrant.FieldGrantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grant_id", values[i])
			} else if value.Valid {
				_m.GrantID = value.String
			}
		case appoauthgrant.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case appoauthgrant.FieldScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Scopes); err != nil {
					return fmt.Errorf("unmarshal field scopes: %w", err)
				}
			}
		case appoauthgrant.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = appoauthgrant.Status(value.String)
			}
		case appoauthgrant.FieldGrantVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grant_version", values[i])
			} else if value.Valid {
				_m.GrantVersion = int(value.Int64)
			}
		case appoauthgrant.FieldFirstAuthorizedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_authorized_at", values[i])
			} else if value.Valid {
				_m.FirstAuthorizedAt = value.Time
			}
		case appoauthgrant.FieldLastAuthorizedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_authorized_at", values[i])
			} else if value.Valid {
				_m.LastAuthorizedAt = value.Time
			}
		case appoauthgrant.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AppOAuthGrant.
// This includes values selected through modifiers, order, etc.
func (_m *AppOAuthGrant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AppOAuthGrant.
// Note that you need to call AppOAuthGrant.Unwrap() before calling this method if this AppOAuthGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AppOAuthGrant) Update() *AppOAuthGrantUpdateOne {
	return NewAppOAuthGrantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AppOAuthGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AppOAuthGrant) Unwrap() *AppOAuthGrant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppOAuthGrant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AppOAuthGrant) String() string {
	var builder strings.Builder
	builder.WriteString("AppOAuthGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("grant_id=")
	builder.WriteString(_m.GrantID)
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scopes))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("grant_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrantVersion))
	builder.WriteString(", ")
	builder.WriteString("first_authorized_at=")
	builder.WriteString(_m.FirstAuthorizedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_authorized_at=")
	builder.WriteString(_m.LastAuthorizedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AppOAuthGrants is a parsable slice of AppOAuthGrant.
type AppOAuthGrants []*AppOAuthGrant
