// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/appoauthsession"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AppOAuthSessionUpdate is the builder for updating AppOAuthSession entities.
type AppOAuthSessionUpdate struct {
	config
	hooks    []Hook
	mutation *AppOAuthSessionMutation
}

// Where appends a list predicates to the AppOAuthSessionUpdate builder.
func (_u *AppOAuthSessionUpdate) Where(ps ...predicate.AppOAuthSession) *AppOAuthSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppOAuthSessionUpdate) SetUpdatedAt(v time.Time) *AppOAuthSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAppGrantID sets the "app_grant_id" field.
func (_u *AppOAuthSessionUpdate) SetAppGrantID(v int64) *AppOAuthSessionUpdate {
	_u.mutation.ResetAppGrantID()
	_u.mutation.SetAppGrantID(v)
	return _u
}

// SetNillableAppGrantID sets the "app_grant_id" field if the given value is not nil.
func (_u *AppOAuthSessionUpdate) SetNillableAppGrantID(v *int64) *AppOAuthSessionUpdate {
	if v != nil {
		_u.SetAppGrantID(*v)
	}
	return _u
}

// AddAppGrantID adds value to the "app_grant_id" field.
func (_u *AppOAuthSessionUpdate) AddAppGrantID(v int64) *AppOAuthSessionUpdate {
	_u.mutation.AddAppGrantID(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AppOAuthSessionUpdate) SetSessionID(v string) *AppOAuthSessionUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AppOAuthSessionUpdate) SetNillableSessionID(v *string) *AppOAuthSessionUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetInstallationIDHash sets the "installation_id_hash" field.
func (_u *AppOAuthSessionUpdate) SetInstallationIDHash(v string) *AppOAuthSessionUpdate {
	_u.mutation.SetInstallationIDHash(v)
	return _u
}

// SetNillableInstallationIDHash sets the "installation_id_hash" field if the given value is not nil.
func (_u *AppOAuthSessionUpdate) SetNillableInstallationIDHash(v *string) *AppOAuthSessionUpdate {
	if v != nil {
		_u.SetInstallationIDHash(*v)
	}
	return _u
}

// SetTokenFamilyID sets the "token_family_id" field.
func (_u *AppOAuthSessionUpdate) SetTokenFamilyID(v string) *AppOAuthSessionUpdate {
	_u.mutation.SetTokenFamilyID(v)
	return _u
}

// SetNillableTokenFamilyID sets the "token_family_id" field if the given value is not nil.
func (_u *AppOAuthSessionUpdate) SetNillableTokenFamilyID(v *string) *AppOAuthSessionUpdate {
	if v != nil {
		_u.SetTokenFamilyID(*v)
	}
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *AppOAuthSessionUpdate) SetDeviceName(v string) *AppOAuthSessionUpdate {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *AppOAuthSessionUpdate) SetNillableDeviceName(v *string) *AppOAuthSessionUpdate {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AppOAuthSessionUpdate) SetPlatform(v string) *AppOAuthSessionUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AppOAuthSessionUpdate) SetNillablePlatform(v *string) *AppOAuthSessionUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AppOAuthSessionUpdate) SetScopes(v []string) *AppOAuthSessionUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AppOAuthSessionUpdate) AppendScopes(v []string) *AppOAuthSessionUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AppOAuthSessionUpdate) SetStatus(v appoauthsession.Status) *AppOAuthSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AppOAuthSessionUpdate) SetNillableStatus(v *appoauthsession.Status) *AppOAuthSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AppOAuthSessionUpdate) SetLastUsedAt(v time.Time) *AppOAuthSessionUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AppOAuthSessionUpdate) SetNillableLastUsedAt(v *time.Time) *AppOAuthSessionUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AppOAuthSessionUpdate) ClearLastUsedAt() *AppOAuthSessionUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AppOAuthSessionUpdate) SetRevokedAt(v time.Time) *AppOAuthSessionUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AppOAuthSessionUpdate) SetNillableRevokedAt(v *time.Time) *AppOAuthSessionUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AppOAuthSessionUpdate) ClearRevokedAt() *AppOAuthSessionUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the AppOAuthSessionMutation object of the builder.
func (_u *AppOAuthSessionUpdate) Mutation() *AppOAuthSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppOAuthSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppOAuthSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppOAuthSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppOAuthSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppOAuthSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := appoauthsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppOAuthSessionUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := appoauthsession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InstallationIDHash(); ok {
		if err := appoauthsession.InstallationIDHashValidator(v); err != nil {
			return &ValidationError{Name: "installation_id_hash", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.installation_id_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenFamilyID(); ok {
		if err := appoauthsession.TokenFamilyIDValidator(v); err != nil {
			return &ValidationError{Name: "token_family_id", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.token_family_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceName(); ok {
		if err := appoauthsession.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.device_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := appoauthsession.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := appoauthsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AppOAuthSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(appoauthsession.Table, appoauthsession.Columns, sqlgraph.NewFieldSpec(appoauthsession.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(appoauthsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AppGrantID(); ok {
		_spec.SetField(appoauthsession.FieldAppGrantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAppGrantID(); ok {
		_spec.AddField(appoauthsession.FieldAppGrantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(appoauthsession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstallationIDHash(); ok {
		_spec.SetField(appoauthsession.FieldInstallationIDHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenFamilyID(); ok {
		_spec.SetField(appoauthsession.FieldTokenFamilyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(appoauthsession.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(appoauthsession.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(appoauthsession.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, appoauthsession.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(appoauthsession.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(appoauthsession.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(appoauthsession.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(appoauthsession.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(appoauthsession.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appoauthsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppOAuthSessionUpdateOne is the builder for updating a single AppOAuthSession entity.
type AppOAuthSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppOAuthSessionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppOAuthSessionUpdateOne) SetUpdatedAt(v time.Time) *AppOAuthSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAppGrantID sets the "app_grant_id" field.
func (_u *AppOAuthSessionUpdateOne) SetAppGrantID(v int64) *AppOAuthSessionUpdateOne {
	_u.mutation.ResetAppGrantID()
	_u.mutation.SetAppGrantID(v)
	return _u
}

// SetNillableAppGrantID sets the "app_grant_id" field if the given value is not nil.
func (_u *AppOAuthSessionUpdateOne) SetNillableAppGrantID(v *int64) *AppOAuthSessionUpdateOne {
	if v != nil {
		_u.SetAppGrantID(*v)
	}
	return _u
}

// AddAppGrantID adds value to the "app_grant_id" field.
func (_u *AppOAuthSessionUpdateOne) AddAppGrantID(v int64) *AppOAuthSessionUpdateOne {
	_u.mutation.AddAppGrantID(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AppOAuthSessionUpdateOne) SetSessionID(v string) *AppOAuthSessionUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AppOAuthSessionUpdateOne) SetNillableSessionID(v *string) *AppOAuthSessionUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetInstallationIDHash sets the "installation_id_hash" field.
func (_u *AppOAuthSessionUpdateOne) SetInstallationIDHash(v string) *AppOAuthSessionUpdateOne {
	_u.mutation.SetInstallationIDHash(v)
	return _u
}

// SetNillableInstallationIDHash sets the "installation_id_hash" field if the given value is not nil.
func (_u *AppOAuthSessionUpdateOne) SetNillableInstallationIDHash(v *string) *AppOAuthSessionUpdateOne {
	if v != nil {
		_u.SetInstallationIDHash(*v)
	}
	return _u
}

// SetTokenFamilyID sets the "token_family_id" field.
func (_u *AppOAuthSessionUpdateOne) SetTokenFamilyID(v string) *AppOAuthSessionUpdateOne {
	_u.mutation.SetTokenFamilyID(v)
	return _u
}

// SetNillableTokenFamilyID sets the "token_family_id" field if the given value is not nil.
func (_u *AppOAuthSessionUpdateOne) SetNillableTokenFamilyID(v *string) *AppOAuthSessionUpdateOne {
	if v != nil {
		_u.SetTokenFamilyID(*v)
	}
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *AppOAuthSessionUpdateOne) SetDeviceName(v string) *AppOAuthSessionUpdateOne {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *AppOAuthSessionUpdateOne) SetNillableDeviceName(v *string) *AppOAuthSessionUpdateOne {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AppOAuthSessionUpdateOne) SetPlatform(v string) *AppOAuthSessionUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AppOAuthSessionUpdateOne) SetNillablePlatform(v *string) *AppOAuthSessionUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AppOAuthSessionUpdateOne) SetScopes(v []string) *AppOAuthSessionUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AppOAuthSessionUpdateOne) AppendScopes(v []string) *AppOAuthSessionUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AppOAuthSessionUpdateOne) SetStatus(v appoauthsession.Status) *AppOAuthSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AppOAuthSessionUpdateOne) SetNillableStatus(v *appoauthsession.Status) *AppOAuthSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AppOAuthSessionUpdateOne) SetLastUsedAt(v time.Time) *AppOAuthSessionUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AppOAuthSessionUpdateOne) SetNillableLastUsedAt(v *time.Time) *AppOAuthSessionUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AppOAuthSessionUpdateOne) ClearLastUsedAt() *AppOAuthSessionUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AppOAuthSessionUpdateOne) SetRevokedAt(v time.Time) *AppOAuthSessionUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AppOAuthSessionUpdateOne) SetNillableRevokedAt(v *time.Time) *AppOAuthSessionUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AppOAuthSessionUpdateOne) ClearRevokedAt() *AppOAuthSessionUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the AppOAuthSessionMutation object of the builder.
func (_u *AppOAuthSessionUpdateOne) Mutation() *AppOAuthSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the AppOAuthSessionUpdate builder.
func (_u *AppOAuthSessionUpdateOne) Where(ps ...predicate.AppOAuthSession) *AppOAuthSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppOAuthSessionUpdateOne) Select(field string, fields ...string) *AppOAuthSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AppOAuthSession entity.
func (_u *AppOAuthSessionUpdateOne) Save(ctx context.Context) (*AppOAuthSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppOAuthSessionUpdateOne) SaveX(ctx context.Context) *AppOAuthSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppOAuthSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppOAuthSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppOAuthSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := appoauthsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppOAuthSessionUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := appoauthsession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InstallationIDHash(); ok {
		if err := appoauthsession.InstallationIDHashValidator(v); err != nil {
			return &ValidationError{Name: "installation_id_hash", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.installation_id_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenFamilyID(); ok {
		if err := appoauthsession.TokenFamilyIDValidator(v); err != nil {
			return &ValidationError{Name: "token_family_id", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.token_family_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceName(); ok {
		if err := appoauthsession.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.device_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := appoauthsession.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := appoauthsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AppOAuthSession.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AppOAuthSessionUpdateOne) sqlSave(ctx context.Context) (_node *AppOAuthSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(appoauthsession.Table, appoauthsession.Columns, sqlgraph.NewFieldSpec(appoauthsession.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppOAuthSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appoauthsession.FieldID)
		for _, f := range fields {
			if !appoauthsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appoauthsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(appoauthsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AppGrantID(); ok {
		_spec.SetField(appoauthsession.FieldAppGrantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAppGrantID(); ok {
		_spec.AddField(appoauthsession.FieldAppGrantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(appoauthsession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstallationIDHash(); ok {
		_spec.SetField(appoauthsession.FieldInstallationIDHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenFamilyID(); ok {
		_spec.SetField(appoauthsession.FieldTokenFamilyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(appoauthsession.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(appoauthsession.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(appoauthsession.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, appoauthsession.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(appoauthsession.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(appoauthsession.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(appoauthsession.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(appoauthsession.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(appoauthsession.FieldRevokedAt, field.TypeTime)
	}
	_node = &AppOAuthSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appoauthsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
