// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/appoauthgrant"
)

// AppOAuthGrantCreate is the builder for creating a AppOAuthGrant entity.
type AppOAuthGrantCreate struct {
	config
	mutation *AppOAuthGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AppOAuthGrantCreate) SetCreatedAt(v time.Time) *AppOAuthGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AppOAuthGrantCreate) SetNillableCreatedAt(v *time.Time) *AppOAuthGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AppOAuthGrantCreate) SetUpdatedAt(v time.Time) *AppOAuthGrantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AppOAuthGrantCreate) SetNillableUpdatedAt(v *time.Time) *AppOAuthGrantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AppOAuthGrantCreate) SetUserID(v int64) *AppOAuthGrantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGrantID sets the "grant_id" field.
func (_c *AppOAuthGrantCreate) SetGrantID(v string) *AppOAuthGrantCreate {
	_c.mutation.SetGrantID(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *AppOAuthGrantCreate) SetClientID(v string) *AppOAuthGrantCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *AppOAuthGrantCreate) SetScopes(v []string) *AppOAuthGrantCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AppOAuthGrantCreate) SetStatus(v appoauthgrant.Status) *AppOAuthGrantCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AppOAuthGrantCreate) SetNillableStatus(v *appoauthgrant.Status) *AppOAuthGrantCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetGrantVersion sets the "grant_version" field.
func (_c *AppOAuthGrantCreate) SetGrantVersion(v int) *AppOAuthGrantCreate {
	_c.mutation.SetGrantVersion(v)
	return _c
}

// SetNillableGrantVersion sets the "grant_version" field if the given value is not nil.
func (_c *AppOAuthGrantCreate) SetNillableGrantVersion(v *int) *AppOAuthGrantCreate {
	if v != nil {
		_c.SetGrantVersion(*v)
	}
	return _c
}

// SetFirstAuthorizedAt sets the "first_authorized_at" field.
func (_c *AppOAuthGrantCreate) SetFirstAuthorizedAt(v time.Time) *AppOAuthGrantCreate {
	_c.mutation.SetFirstAuthorizedAt(v)
	return _c
}

// SetNillableFirstAuthorizedAt sets the "first_authorized_at" field if the given value is not nil.
func (_c *AppOAuthGrantCreate) SetNillableFirstAuthorizedAt(v *time.Time) *AppOAuthGrantCreate {
	if v != nil {
		_c.SetFirstAuthorizedAt(*v)
	}
	return _c
}

// SetLastAuthorizedAt sets the "last_authorized_at" field.
func (_c *AppOAuthGrantCreate) SetLastAuthorizedAt(v time.Time) *AppOAuthGrantCreate {
	_c.mutation.SetLastAuthorizedAt(v)
	return _c
}

// SetNillableLastAuthorizedAt sets the "last_authorized_at" field if the given value is not nil.
func (_c *AppOAuthGrantCreate) SetNillableLastAuthorizedAt(v *time.Time) *AppOAuthGrantCreate {
	if v != nil {
		_c.SetLastAuthorizedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *AppOAuthGrantCreate) SetRevokedAt(v time.Time) *AppOAuthGrantCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *AppOAuthGrantCreate) SetNillableRevokedAt(v *time.Time) *AppOAuthGrantCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// Mutation returns the AppOAuthGrantMutation object of the builder.
func (_c *AppOAuthGrantCreate) Mutation() *AppOAuthGrantMutation {
	return _c.mutation
}

// Save creates the AppOAuthGrant in the database.
func (_c *AppOAuthGrantCreate) Save(ctx context.Context) (*AppOAuthGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppOAuthGrantCreate) SaveX(ctx context.Context) *AppOAuthGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppOAuthGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppOAuthGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppOAuthGrantCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := appoauthgrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := appoauthgrant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		v := appoauthgrant.DefaultScopes()
		_c.mutation.SetScopes(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := appoauthgrant.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.GrantVersion(); !ok {
		v := appoauthgrant.DefaultGrantVersion
		_c.mutation.SetGrantVersion(v)
	}
	if _, ok := _c.mutation.FirstAuthorizedAt(); !ok {
		v := appoauthgrant.DefaultFirstAuthorizedAt()
		_c.mutation.SetFirstAuthorizedAt(v)
	}
	if _, ok := _c.mutation.LastAuthorizedAt(); !ok {
		v := appoauthgrant.DefaultLastAuthorizedAt()
		_c.mutation.SetLastAuthorizedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppOAuthGrantCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AppOAuthGrant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AppOAuthGrant.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AppOAuthGrant.user_id"`)}
	}
	if _, ok := _c.mutation.GrantID(); !ok {
		return &ValidationError{Name: "grant_id", err: errors.New(`ent: missing required field "AppOAuthGrant.grant_id"`)}
	}
	if v, ok := _c.mutation.GrantID(); ok {
		if err := appoauthgrant.GrantIDValidator(v); err != nil {
			return &ValidationError{Name: "grant_id", err: fmt.Errorf(`ent: validator failed for field "AppOAuthGrant.grant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "AppOAuthGrant.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := appoauthgrant.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "AppOAuthGrant.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "AppOAuthGrant.scopes"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AppOAuthGrant.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := appoauthgrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AppOAuthGrant.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GrantVersion(); !ok {
		return &ValidationError{Name: "grant_version", err: errors.New(`ent: missing required field "AppOAuthGrant.grant_version"`)}
	}
	if v, ok := _c.mutation.GrantVersion(); ok {
		if err := appoauthgrant.GrantVersionValidator(v); err != nil {
			return &ValidationError{Name: "grant_version", err: fmt.Errorf(`ent: validator failed for field "AppOAuthGrant.grant_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FirstAuthorizedAt(); !ok {
		return &ValidationError{Name: "first_authorized_at", err: errors.New(`ent: missing required field "AppOAuthGrant.first_authorized_at"`)}
	}
	if _, ok := _c.mutation.LastAuthorizedAt(); !ok {
		return &ValidationError{Name: "last_authorized_at", err: errors.New(`ent: missing required field "AppOAuthGrant.last_authorized_at"`)}
	}
	return nil
}

func (_c *AppOAuthGrantCreate) sqlSave(ctx context.Context) (*AppOAuthGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppOAuthGrantCreate) createSpec() (*AppOAuthGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &AppOAuthGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(appoauthgrant.Table, sqlgraph.NewFieldSpec(appoauthgrant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(appoauthgrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(appoauthgrant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(appoauthgrant.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GrantID(); ok {
		_spec.SetField(appoauthgrant.FieldGrantID, field.TypeString, value)
		_node.GrantID = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(appoauthgrant.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(appoauthgrant.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(appoauthgrant.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.GrantVersion(); ok {
		_spec.SetField(appoauthgrant.FieldGrantVersion, field.TypeInt, value)
		_node.GrantVersion = value
	}
	if value, ok := _c.mutation.FirstAuthorizedAt(); ok {
		_spec.SetField(appoauthgrant.FieldFirstAuthorizedAt, field.TypeTime, value)
		_node.FirstAuthorizedAt = value
	}
	if value, ok := _c.mutation.LastAuthorizedAt(); ok {
		_spec.SetField(appoauthgrant.FieldLastAuthorizedAt, field.TypeTime, value)
		_node.LastAuthorizedAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(appoauthgrant.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppOAuthGrant.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AppOAuthGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AppOAuthGrantCreate) OnConflict(opts ...sql.ConflictOption) *AppOAuthGrantUpsertOne {
	_c.conflict = opts
	return &AppOAuthGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppOAuthGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AppOAuthGrantCreate) OnConflictColumns(columns ...string) *AppOAuthGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AppOAuthGrantUpsertOne{
		create: _c,
	}
}

type (
	// AppOAuthGrantUpsertOne is the builder for "upsert"-ing
	//  one AppOAuthGrant node.
	AppOAuthGrantUpsertOne struct {
		create *AppOAuthGrantCreate
	}

	// AppOAuthGrantUpsert is the "OnConflict" setter.
	AppOAuthGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AppOAuthGrantUpsert) SetUpdatedAt(v time.Time) *AppOAuthGrantUpsert {
	u.Set(appoauthgrant.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppOAuthGrantUpsert) UpdateUpdatedAt() *AppOAuthGrantUpsert {
	u.SetExcluded(appoauthgrant.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AppOAuthGrantUpsert) SetUserID(v int64) *AppOAuthGrantUpsert {
	u.Set(appoauthgrant.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AppOAuthGrantUpsert) UpdateUserID() *AppOAuthGrantUpsert {
	u.SetExcluded(appoauthgrant.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *AppOAuthGrantUpsert) AddUserID(v int64) *AppOAuthGrantUpsert {
	u.Add(appoauthgrant.FieldUserID, v)
	return u
}

// SetGrantID sets the "grant_id" field.
func (u *AppOAuthGrantUpsert) SetGrantID(v string) *AppOAuthGrantUpsert {
	u.Set(appoauthgrant.FieldGrantID, v)
	return u
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *AppOAuthGrantUpsert) UpdateGrantID() *AppOAuthGrantUpsert {
	u.SetExcluded(appoauthgrant.FieldGrantID)
	return u
}

// SetClientID sets the "client_id" field.
func (u *AppOAuthGrantUpsert) SetClientID(v string) *AppOAuthGrantUpsert {
	u.Set(appoauthgrant.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AppOAuthGrantUpsert) UpdateClientID() *AppOAuthGrantUpsert {
	u.SetExcluded(appoauthgrant.FieldClientID)
	return u
}

// SetScopes sets the "scopes" field.
func (u *AppOAuthGrantUpsert) SetScopes(v []string) *AppOAuthGrantUpsert {
	u.Set(appoauthgrant.FieldScopes, v)
	return u
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AppOAuthGrantUpsert) UpdateScopes() *AppOAuthGrantUpsert {
	u.SetExcluded(appoauthgrant.FieldScopes)
	return u
}

// SetStatus sets the "status" field.
func (u *AppOAuthGrantUpsert) SetStatus(v appoauthgrant.Status) *AppOAuthGrantUpsert {
	u.Set(appoauthgrant.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AppOAuthGrantUpsert) UpdateStatus() *AppOAuthGrantUpsert {
	u.SetExcluded(appoauthgrant.FieldStatus)
	return u
}

// SetGrantVersion sets the "grant_version" field.
func (u *AppOAuthGrantUpsert) SetGrantVersion(v int) *AppOAuthGrantUpsert {
	u.Set(appoauthgrant.FieldGrantVersion, v)
	return u
}

// UpdateGrantVersion sets the "grant_version" field to the value that was provided on create.
func (u *AppOAuthGrantUpsert) UpdateGrantVersion() *AppOAuthGrantUpsert {
	u.SetExcluded(appoauthgrant.FieldGrantVersion)
	return u
}

// AddGrantVersion adds v to the "grant_version" field.
func (u *AppOAuthGrantUpsert) AddGrantVersion(v int) *AppOAuthGrantUpsert {
	u.Add(appoauthgrant.FieldGrantVersion, v)
	return u
}

// SetFirstAuthorizedAt sets the "first_authorized_at" field.
func (u *AppOAuthGrantUpsert) SetFirstAuthorizedAt(v time.Time) *AppOAuthGrantUpsert {
	u.Set(appoauthgrant.FieldFirstAuthorizedAt, v)
	return u
}

// UpdateFirstAuthorizedAt sets the "first_authorized_at" field to the value that was provided on create.
func (u *AppOAuthGrantUpsert) UpdateFirstAuthorizedAt() *AppOAuthGrantUpsert {
	u.SetExcluded(appoauthgrant.FieldFirstAuthorizedAt)
	return u
}

// SetLastAuthorizedAt sets the "last_authorized_at" field.
func (u *AppOAuthGrantUpsert) SetLastAuthorizedAt(v time.Time) *AppOAuthGrantUpsert {
	u.Set(appoauthgrant.FieldLastAuthorizedAt, v)
	return u
}

// UpdateLastAuthorizedAt sets the "last_authorized_at" field to the value that was provided on create.
func (u *AppOAuthGrantUpsert) UpdateLastAuthorizedAt() *AppOAuthGrantUpsert {
	u.SetExcluded(appoauthgrant.FieldLastAuthorizedAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AppOAuthGrantUpsert) SetRevokedAt(v time.Time) *AppOAuthGrantUpsert {
	u.Set(appoauthgrant.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AppOAuthGrantUpsert) UpdateRevokedAt() *AppOAuthGrantUpsert {
	u.SetExcluded(appoauthgrant.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AppOAuthGrantUpsert) ClearRevokedAt() *AppOAuthGrantUpsert {
	u.SetNull(appoauthgrant.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AppOAuthGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AppOAuthGrantUpsertOne) UpdateNewValues() *AppOAuthGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(appoauthgrant.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AppOAuthGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AppOAuthGrantUpsertOne) Ignore() *AppOAuthGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppOAuthGrantUpsertOne) DoNothing() *AppOAuthGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppOAuthGrantCreate.OnConflict
// documentation for more info.
func (u *AppOAuthGrantUpsertOne) Update(set func(*AppOAuthGrantUpsert)) *AppOAuthGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppOAuthGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppOAuthGrantUpsertOne) SetUpdatedAt(v time.Time) *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertOne) UpdateUpdatedAt() *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *AppOAuthGrantUpsertOne) SetUserID(v int64) *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AppOAuthGrantUpsertOne) AddUserID(v int64) *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertOne) UpdateUserID() *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetGrantID sets the "grant_id" field.
func (u *AppOAuthGrantUpsertOne) SetGrantID(v string) *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertOne) UpdateGrantID() *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateGrantID()
	})
}

// SetClientID sets the "client_id" field.
func (u *AppOAuthGrantUpsertOne) SetClientID(v string) *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertOne) UpdateClientID() *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateClientID()
	})
}

// SetScopes sets the "scopes" field.
func (u *AppOAuthGrantUpsertOne) SetScopes(v []string) *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertOne) UpdateScopes() *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateScopes()
	})
}

// SetStatus sets the "status" field.
func (u *AppOAuthGrantUpsertOne) SetStatus(v appoauthgrant.Status) *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertOne) UpdateStatus() *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateStatus()
	})
}

// SetGrantVersion sets the "grant_version" field.
func (u *AppOAuthGrantUpsertOne) SetGrantVersion(v int) *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetGrantVersion(v)
	})
}

// AddGrantVersion adds v to the "grant_version" field.
func (u *AppOAuthGrantUpsertOne) AddGrantVersion(v int) *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.AddGrantVersion(v)
	})
}

// UpdateGrantVersion sets the "grant_version" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertOne) UpdateGrantVersion() *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateGrantVersion()
	})
}

// SetFirstAuthorizedAt sets the "first_authorized_at" field.
func (u *AppOAuthGrantUpsertOne) SetFirstAuthorizedAt(v time.Time) *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetFirstAuthorizedAt(v)
	})
}

// UpdateFirstAuthorizedAt sets the "first_authorized_at" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertOne) UpdateFirstAuthorizedAt() *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateFirstAuthorizedAt()
	})
}

// SetLastAuthorizedAt sets the "last_authorized_at" field.
func (u *AppOAuthGrantUpsertOne) SetLastAuthorizedAt(v time.Time) *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetLastAuthorizedAt(v)
	})
}

// UpdateLastAuthorizedAt sets the "last_authorized_at" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertOne) UpdateLastAuthorizedAt() *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateLastAuthorizedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AppOAuthGrantUpsertOne) SetRevokedAt(v time.Time) *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertOne) UpdateRevokedAt() *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AppOAuthGrantUpsertOne) ClearRevokedAt() *AppOAuthGrantUpsertOne {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *AppOAuthGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppOAuthGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppOAuthGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AppOAuthGrantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AppOAuthGrantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AppOAuthGrantCreateBulk is the builder for creating many AppOAuthGrant entities in bulk.
type AppOAuthGrantCreateBulk struct {
	config
	err      error
	builders []*AppOAuthGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the AppOAuthGrant entities in the database.
func (_c *AppOAuthGrantCreateBulk) Save(ctx context.Context) ([]*AppOAuthGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AppOAuthGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppOAuthGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppOAuthGrantCreateBulk) SaveX(ctx context.Context) []*AppOAuthGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppOAuthGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppOAuthGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppOAuthGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AppOAuthGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AppOAuthGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *AppOAuthGrantUpsertBulk {
	_c.conflict = opts
	return &AppOAuthGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppOAuthGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AppOAuthGrantCreateBulk) OnConflictColumns(columns ...string) *AppOAuthGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AppOAuthGrantUpsertBulk{
		create: _c,
	}
}

// AppOAuthGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of AppOAuthGrant nodes.
type AppOAuthGrantUpsertBulk struct {
	create *AppOAuthGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AppOAuthGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AppOAuthGrantUpsertBulk) UpdateNewValues() *AppOAuthGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(appoauthgrant.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AppOAuthGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AppOAuthGrantUpsertBulk) Ignore() *AppOAuthGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppOAuthGrantUpsertBulk) DoNothing() *AppOAuthGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppOAuthGrantCreateBulk.OnConflict
// documentation for more info.
func (u *AppOAuthGrantUpsertBulk) Update(set func(*AppOAuthGrantUpsert)) *AppOAuthGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppOAuthGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppOAuthGrantUpsertBulk) SetUpdatedAt(v time.Time) *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertBulk) UpdateUpdatedAt() *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *AppOAuthGrantUpsertBulk) SetUserID(v int64) *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AppOAuthGrantUpsertBulk) AddUserID(v int64) *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertBulk) UpdateUserID() *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetGrantID sets the "grant_id" field.
func (u *AppOAuthGrantUpsertBulk) SetGrantID(v string) *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertBulk) UpdateGrantID() *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateGrantID()
	})
}

// SetClientID sets the "client_id" field.
func (u *AppOAuthGrantUpsertBulk) SetClientID(v string) *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertBulk) UpdateClientID() *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateClientID()
	})
}

// SetScopes sets the "scopes" field.
func (u *AppOAuthGrantUpsertBulk) SetScopes(v []string) *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertBulk) UpdateScopes() *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateScopes()
	})
}

// SetStatus sets the "status" field.
func (u *AppOAuthGrantUpsertBulk) SetStatus(v appoauthgrant.Status) *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertBulk) UpdateStatus() *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateStatus()
	})
}

// SetGrantVersion sets the "grant_version" field.
func (u *AppOAuthGrantUpsertBulk) SetGrantVersion(v int) *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetGrantVersion(v)
	})
}

// AddGrantVersion adds v to the "grant_version" field.
func (u *AppOAuthGrantUpsertBulk) AddGrantVersion(v int) *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.AddGrantVersion(v)
	})
}

// UpdateGrantVersion sets the "grant_version" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertBulk) UpdateGrantVersion() *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateGrantVersion()
	})
}

// SetFirstAuthorizedAt sets the "first_authorized_at" field.
func (u *AppOAuthGrantUpsertBulk) SetFirstAuthorizedAt(v time.Time) *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetFirstAuthorizedAt(v)
	})
}

// UpdateFirstAuthorizedAt sets the "first_authorized_at" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertBulk) UpdateFirstAuthorizedAt() *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateFirstAuthorizedAt()
	})
}

// SetLastAuthorizedAt sets the "last_authorized_at" field.
func (u *AppOAuthGrantUpsertBulk) SetLastAuthorizedAt(v time.Time) *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetLastAuthorizedAt(v)
	})
}

// UpdateLastAuthorizedAt sets the "last_authorized_at" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertBulk) UpdateLastAuthorizedAt() *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateLastAuthorizedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AppOAuthGrantUpsertBulk) SetRevokedAt(v time.Time) *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AppOAuthGrantUpsertBulk) UpdateRevokedAt() *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AppOAuthGrantUpsertBulk) ClearRevokedAt() *AppOAuthGrantUpsertBulk {
	return u.Update(func(s *AppOAuthGrantUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *AppOAuthGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AppOAuthGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppOAuthGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppOAuthGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
