// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/appoauthgrant"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AppOAuthGrantDelete is the builder for deleting a AppOAuthGrant entity.
type AppOAuthGrantDelete struct {
	config
	hooks    []Hook
	mutation *AppOAuthGrantMutation
}

// Where appends a list predicates to the AppOAuthGrantDelete builder.
func (_d *AppOAuthGrantDelete) Where(ps ...predicate.AppOAuthGrant) *AppOAuthGrantDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AppOAuthGrantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AppOAuthGrantDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AppOAuthGrantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(appoauthgrant.Table, sqlgraph.NewFieldSpec(appoauthgrant.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AppOAuthGrantDeleteOne is the builder for deleting a single AppOAuthGrant entity.
type AppOAuthGrantDeleteOne struct {
	_d *AppOAuthGrantDelete
}

// Where appends a list predicates to the AppOAuthGrantDelete builder.
func (_d *AppOAuthGrantDeleteOne) Where(ps ...predicate.AppOAuthGrant) *AppOAuthGrantDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AppOAuthGrantDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{appoauthgrant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AppOAuthGrantDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
