// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/ticketmessage"
)

// TicketAttachmentCreate is the builder for creating a TicketAttachment entity.
type TicketAttachmentCreate struct {
	config
	mutation *TicketAttachmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMessageID sets the "message_id" field.
func (_c *TicketAttachmentCreate) SetMessageID(v int64) *TicketAttachmentCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetObjectKey sets the "object_key" field.
func (_c *TicketAttachmentCreate) SetObjectKey(v string) *TicketAttachmentCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetOriginalName sets the "original_name" field.
func (_c *TicketAttachmentCreate) SetOriginalName(v string) *TicketAttachmentCreate {
	_c.mutation.SetOriginalName(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *TicketAttachmentCreate) SetContentType(v string) *TicketAttachmentCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *TicketAttachmentCreate) SetSizeBytes(v int64) *TicketAttachmentCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *TicketAttachmentCreate) SetSha256(v string) *TicketAttachmentCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TicketAttachmentCreate) SetCreatedAt(v time.Time) *TicketAttachmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableCreatedAt(v *time.Time) *TicketAttachmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetMessage sets the "message" edge to the TicketMessage entity.
func (_c *TicketAttachmentCreate) SetMessage(v *TicketMessage) *TicketAttachmentCreate {
	return _c.SetMessageID(v.ID)
}

// Mutation returns the TicketAttachmentMutation object of the builder.
func (_c *TicketAttachmentCreate) Mutation() *TicketAttachmentMutation {
	return _c.mutation
}

// Save creates the TicketAttachment in the database.
func (_c *TicketAttachmentCreate) Save(ctx context.Context) (*TicketAttachment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketAttachmentCreate) SaveX(ctx context.Context) *TicketAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketAttachmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketAttachmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketAttachmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ticketattachment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketAttachmentCreate) check() error {
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "TicketAttachment.message_id"`)}
	}
	if _, ok := _c.mutation.ObjectKey(); !ok {
		return &ValidationError{Name: "object_key", err: errors.New(`ent: missing required field "TicketAttachment.object_key"`)}
	}
	if v, ok := _c.mutation.ObjectKey(); ok {
		if err := ticketattachment.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.object_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginalName(); !ok {
		return &ValidationError{Name: "original_name", err: errors.New(`ent: missing required field "TicketAttachment.original_name"`)}
	}
	if v, ok := _c.mutation.OriginalName(); ok {
		if err := ticketattachment.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.original_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "TicketAttachment.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := ticketattachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "TicketAttachment.size_bytes"`)}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "TicketAttachment.sha256"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := ticketattachment.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TicketAttachment.created_at"`)}
	}
	if len(_c.mutation.MessageIDs()) == 0 {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required edge "TicketAttachment.message"`)}
	}
	return nil
}

func (_c *TicketAttachmentCreate) sqlSave(ctx context.Context) (*TicketAttachment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketAttachmentCreate) createSpec() (*TicketAttachment, *sqlgraph.CreateSpec) {
	var (
		_node = &TicketAttachment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticketattachment.Table, sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(ticketattachment.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = value
	}
	if value, ok := _c.mutation.OriginalName(); ok {
		_spec.SetField(ticketattachment.FieldOriginalName, field.TypeString, value)
		_node.OriginalName = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(ticketattachment.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(ticketattachment.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(ticketattachment.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ticketattachment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketattachment.MessageTable,
			Columns: []string{ticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketAttachment.Create().
//		SetMessageID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketAttachmentUpsert) {
//			SetMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketAttachmentCreate) OnConflict(opts ...sql.ConflictOption) *TicketAttachmentUpsertOne {
	_c.conflict = opts
	return &TicketAttachmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketAttachmentCreate) OnConflictColumns(columns ...string) *TicketAttachmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketAttachmentUpsertOne{
		create: _c,
	}
}

type (
	// TicketAttachmentUpsertOne is the builder for "upsert"-ing
	//  one TicketAttachment node.
	TicketAttachmentUpsertOne struct {
		create *TicketAttachmentCreate
	}

	// TicketAttachmentUpsert is the "OnConflict" setter.
	TicketAttachmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetMessageID sets the "message_id" field.
func (u *TicketAttachmentUpsert) SetMessageID(v int64) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldMessageID, v)
	return u
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateMessageID() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldMessageID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketAttachmentUpsertOne) UpdateNewValues() *TicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ObjectKey(); exists {
			s.SetIgnore(ticketattachment.FieldObjectKey)
		}
		if _, exists := u.create.mutation.OriginalName(); exists {
			s.SetIgnore(ticketattachment.FieldOriginalName)
		}
		if _, exists := u.create.mutation.ContentType(); exists {
			s.SetIgnore(ticketattachment.FieldContentType)
		}
		if _, exists := u.create.mutation.SizeBytes(); exists {
			s.SetIgnore(ticketattachment.FieldSizeBytes)
		}
		if _, exists := u.create.mutation.Sha256(); exists {
			s.SetIgnore(ticketattachment.FieldSha256)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ticketattachment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TicketAttachmentUpsertOne) Ignore() *TicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketAttachmentUpsertOne) DoNothing() *TicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketAttachmentCreate.OnConflict
// documentation for more info.
func (u *TicketAttachmentUpsertOne) Update(set func(*TicketAttachmentUpsert)) *TicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetMessageID sets the "message_id" field.
func (u *TicketAttachmentUpsertOne) SetMessageID(v int64) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateMessageID() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateMessageID()
	})
}

// Exec executes the query.
func (u *TicketAttachmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketAttachmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketAttachmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TicketAttachmentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TicketAttachmentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TicketAttachmentCreateBulk is the builder for creating many TicketAttachment entities in bulk.
type TicketAttachmentCreateBulk struct {
	config
	err      error
	builders []*TicketAttachmentCreate
	conflict []sql.ConflictOption
}

// Save creates the TicketAttachment entities in the database.
func (_c *TicketAttachmentCreateBulk) Save(ctx context.Context) ([]*TicketAttachment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TicketAttachment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketAttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketAttachmentCreateBulk) SaveX(ctx context.Context) []*TicketAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketAttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketAttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketAttachment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketAttachmentUpsert) {
//			SetMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketAttachmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *TicketAttachmentUpsertBulk {
	_c.conflict = opts
	return &TicketAttachmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketAttachmentCreateBulk) OnConflictColumns(columns ...string) *TicketAttachmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketAttachmentUpsertBulk{
		create: _c,
	}
}

// TicketAttachmentUpsertBulk is the builder for "upsert"-ing
// a bulk of TicketAttachment nodes.
type TicketAttachmentUpsertBulk struct {
	create *TicketAttachmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketAttachmentUpsertBulk) UpdateNewValues() *TicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ObjectKey(); exists {
				s.SetIgnore(ticketattachment.FieldObjectKey)
			}
			if _, exists := b.mutation.OriginalName(); exists {
				s.SetIgnore(ticketattachment.FieldOriginalName)
			}
			if _, exists := b.mutation.ContentType(); exists {
				s.SetIgnore(ticketattachment.FieldContentType)
			}
			if _, exists := b.mutation.SizeBytes(); exists {
				s.SetIgnore(ticketattachment.FieldSizeBytes)
			}
			if _, exists := b.mutation.Sha256(); exists {
				s.SetIgnore(ticketattachment.FieldSha256)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ticketattachment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TicketAttachmentUpsertBulk) Ignore() *TicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketAttachmentUpsertBulk) DoNothing() *TicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketAttachmentCreateBulk.OnConflict
// documentation for more info.
func (u *TicketAttachmentUpsertBulk) Update(set func(*TicketAttachmentUpsert)) *TicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetMessageID sets the "message_id" field.
func (u *TicketAttachmentUpsertBulk) SetMessageID(v int64) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateMessageID() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateMessageID()
	})
}

// Exec executes the query.
func (u *TicketAttachmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TicketAttachmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketAttachmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketAttachmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
