// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketcategory"
)

// TicketCategoryCreate is the builder for creating a TicketCategory entity.
type TicketCategoryCreate struct {
	config
	mutation *TicketCategoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (_c *TicketCategoryCreate) SetCode(v string) *TicketCategoryCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNameZh sets the "name_zh" field.
func (_c *TicketCategoryCreate) SetNameZh(v string) *TicketCategoryCreate {
	_c.mutation.SetNameZh(v)
	return _c
}

// SetNameEn sets the "name_en" field.
func (_c *TicketCategoryCreate) SetNameEn(v string) *TicketCategoryCreate {
	_c.mutation.SetNameEn(v)
	return _c
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (_c *TicketCategoryCreate) SetNillableNameEn(v *string) *TicketCategoryCreate {
	if v != nil {
		_c.SetNameEn(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *TicketCategoryCreate) SetActive(v bool) *TicketCategoryCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *TicketCategoryCreate) SetNillableActive(v *bool) *TicketCategoryCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *TicketCategoryCreate) SetSortOrder(v int) *TicketCategoryCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *TicketCategoryCreate) SetNillableSortOrder(v *int) *TicketCategoryCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TicketCategoryCreate) SetCreatedAt(v time.Time) *TicketCategoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TicketCategoryCreate) SetNillableCreatedAt(v *time.Time) *TicketCategoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TicketCategoryCreate) SetUpdatedAt(v time.Time) *TicketCategoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TicketCategoryCreate) SetNillableUpdatedAt(v *time.Time) *TicketCategoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_c *TicketCategoryCreate) AddTicketIDs(ids ...int64) *TicketCategoryCreate {
	_c.mutation.AddTicketIDs(ids...)
	return _c
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_c *TicketCategoryCreate) AddTickets(v ...*Ticket) *TicketCategoryCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTicketIDs(ids...)
}

// Mutation returns the TicketCategoryMutation object of the builder.
func (_c *TicketCategoryCreate) Mutation() *TicketCategoryMutation {
	return _c.mutation
}

// Save creates the TicketCategory in the database.
func (_c *TicketCategoryCreate) Save(ctx context.Context) (*TicketCategory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketCategoryCreate) SaveX(ctx context.Context) *TicketCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketCategoryCreate) defaults() {
	if _, ok := _c.mutation.NameEn(); !ok {
		v := ticketcategory.DefaultNameEn
		_c.mutation.SetNameEn(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := ticketcategory.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := ticketcategory.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ticketcategory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ticketcategory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketCategoryCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "TicketCategory.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := ticketcategory.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "TicketCategory.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameZh(); !ok {
		return &ValidationError{Name: "name_zh", err: errors.New(`ent: missing required field "TicketCategory.name_zh"`)}
	}
	if v, ok := _c.mutation.NameZh(); ok {
		if err := ticketcategory.NameZhValidator(v); err != nil {
			return &ValidationError{Name: "name_zh", err: fmt.Errorf(`ent: validator failed for field "TicketCategory.name_zh": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameEn(); !ok {
		return &ValidationError{Name: "name_en", err: errors.New(`ent: missing required field "TicketCategory.name_en"`)}
	}
	if v, ok := _c.mutation.NameEn(); ok {
		if err := ticketcategory.NameEnValidator(v); err != nil {
			return &ValidationError{Name: "name_en", err: fmt.Errorf(`ent: validator failed for field "TicketCategory.name_en": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "TicketCategory.active"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "TicketCategory.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TicketCategory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TicketCategory.updated_at"`)}
	}
	return nil
}

func (_c *TicketCategoryCreate) sqlSave(ctx context.Context) (*TicketCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketCategoryCreate) createSpec() (*TicketCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &TicketCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticketcategory.Table, sqlgraph.NewFieldSpec(ticketcategory.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(ticketcategory.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.NameZh(); ok {
		_spec.SetField(ticketcategory.FieldNameZh, field.TypeString, value)
		_node.NameZh = value
	}
	if value, ok := _c.mutation.NameEn(); ok {
		_spec.SetField(ticketcategory.FieldNameEn, field.TypeString, value)
		_node.NameEn = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(ticketcategory.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(ticketcategory.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ticketcategory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ticketcategory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketcategory.TicketsTable,
			Columns: []string{ticketcategory.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketCategory.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketCategoryUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketCategoryCreate) OnConflict(opts ...sql.ConflictOption) *TicketCategoryUpsertOne {
	_c.conflict = opts
	return &TicketCategoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketCategory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketCategoryCreate) OnConflictColumns(columns ...string) *TicketCategoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketCategoryUpsertOne{
		create: _c,
	}
}

type (
	// TicketCategoryUpsertOne is the builder for "upsert"-ing
	//  one TicketCategory node.
	TicketCategoryUpsertOne struct {
		create *TicketCategoryCreate
	}

	// TicketCategoryUpsert is the "OnConflict" setter.
	TicketCategoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetNameZh sets the "name_zh" field.
func (u *TicketCategoryUpsert) SetNameZh(v string) *TicketCategoryUpsert {
	u.Set(ticketcategory.FieldNameZh, v)
	return u
}

// UpdateNameZh sets the "name_zh" field to the value that was provided on create.
func (u *TicketCategoryUpsert) UpdateNameZh() *TicketCategoryUpsert {
	u.SetExcluded(ticketcategory.FieldNameZh)
	return u
}

// SetNameEn sets the "name_en" field.
func (u *TicketCategoryUpsert) SetNameEn(v string) *TicketCategoryUpsert {
	u.Set(ticketcategory.FieldNameEn, v)
	return u
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *TicketCategoryUpsert) UpdateNameEn() *TicketCategoryUpsert {
	u.SetExcluded(ticketcategory.FieldNameEn)
	return u
}

// SetActive sets the "active" field.
func (u *TicketCategoryUpsert) SetActive(v bool) *TicketCategoryUpsert {
	u.Set(ticketcategory.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *TicketCategoryUpsert) UpdateActive() *TicketCategoryUpsert {
	u.SetExcluded(ticketcategory.FieldActive)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *TicketCategoryUpsert) SetSortOrder(v int) *TicketCategoryUpsert {
	u.Set(ticketcategory.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *TicketCategoryUpsert) UpdateSortOrder() *TicketCategoryUpsert {
	u.SetExcluded(ticketcategory.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *TicketCategoryUpsert) AddSortOrder(v int) *TicketCategoryUpsert {
	u.Add(ticketcategory.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TicketCategoryUpsert) SetUpdatedAt(v time.Time) *TicketCategoryUpsert {
	u.Set(ticketcategory.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TicketCategoryUpsert) UpdateUpdatedAt() *TicketCategoryUpsert {
	u.SetExcluded(ticketcategory.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TicketCategory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketCategoryUpsertOne) UpdateNewValues() *TicketCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.Code(); exists {
			s.SetIgnore(ticketcategory.FieldCode)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ticketcategory.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketCategory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TicketCategoryUpsertOne) Ignore() *TicketCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketCategoryUpsertOne) DoNothing() *TicketCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketCategoryCreate.OnConflict
// documentation for more info.
func (u *TicketCategoryUpsertOne) Update(set func(*TicketCategoryUpsert)) *TicketCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketCategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetNameZh sets the "name_zh" field.
func (u *TicketCategoryUpsertOne) SetNameZh(v string) *TicketCategoryUpsertOne {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.SetNameZh(v)
	})
}

// UpdateNameZh sets the "name_zh" field to the value that was provided on create.
func (u *TicketCategoryUpsertOne) UpdateNameZh() *TicketCategoryUpsertOne {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.UpdateNameZh()
	})
}

// SetNameEn sets the "name_en" field.
func (u *TicketCategoryUpsertOne) SetNameEn(v string) *TicketCategoryUpsertOne {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.SetNameEn(v)
	})
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *TicketCategoryUpsertOne) UpdateNameEn() *TicketCategoryUpsertOne {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.UpdateNameEn()
	})
}

// SetActive sets the "active" field.
func (u *TicketCategoryUpsertOne) SetActive(v bool) *TicketCategoryUpsertOne {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *TicketCategoryUpsertOne) UpdateActive() *TicketCategoryUpsertOne {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.UpdateActive()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *TicketCategoryUpsertOne) SetSortOrder(v int) *TicketCategoryUpsertOne {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *TicketCategoryUpsertOne) AddSortOrder(v int) *TicketCategoryUpsertOne {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *TicketCategoryUpsertOne) UpdateSortOrder() *TicketCategoryUpsertOne {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TicketCategoryUpsertOne) SetUpdatedAt(v time.Time) *TicketCategoryUpsertOne {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TicketCategoryUpsertOne) UpdateUpdatedAt() *TicketCategoryUpsertOne {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TicketCategoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketCategoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketCategoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TicketCategoryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TicketCategoryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TicketCategoryCreateBulk is the builder for creating many TicketCategory entities in bulk.
type TicketCategoryCreateBulk struct {
	config
	err      error
	builders []*TicketCategoryCreate
	conflict []sql.ConflictOption
}

// Save creates the TicketCategory entities in the database.
func (_c *TicketCategoryCreateBulk) Save(ctx context.Context) ([]*TicketCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TicketCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketCategoryCreateBulk) SaveX(ctx context.Context) []*TicketCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketCategory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketCategoryUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketCategoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *TicketCategoryUpsertBulk {
	_c.conflict = opts
	return &TicketCategoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketCategory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketCategoryCreateBulk) OnConflictColumns(columns ...string) *TicketCategoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketCategoryUpsertBulk{
		create: _c,
	}
}

// TicketCategoryUpsertBulk is the builder for "upsert"-ing
// a bulk of TicketCategory nodes.
type TicketCategoryUpsertBulk struct {
	create *TicketCategoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TicketCategory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketCategoryUpsertBulk) UpdateNewValues() *TicketCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.Code(); exists {
				s.SetIgnore(ticketcategory.FieldCode)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ticketcategory.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketCategory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TicketCategoryUpsertBulk) Ignore() *TicketCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketCategoryUpsertBulk) DoNothing() *TicketCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketCategoryCreateBulk.OnConflict
// documentation for more info.
func (u *TicketCategoryUpsertBulk) Update(set func(*TicketCategoryUpsert)) *TicketCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketCategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetNameZh sets the "name_zh" field.
func (u *TicketCategoryUpsertBulk) SetNameZh(v string) *TicketCategoryUpsertBulk {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.SetNameZh(v)
	})
}

// UpdateNameZh sets the "name_zh" field to the value that was provided on create.
func (u *TicketCategoryUpsertBulk) UpdateNameZh() *TicketCategoryUpsertBulk {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.UpdateNameZh()
	})
}

// SetNameEn sets the "name_en" field.
func (u *TicketCategoryUpsertBulk) SetNameEn(v string) *TicketCategoryUpsertBulk {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.SetNameEn(v)
	})
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *TicketCategoryUpsertBulk) UpdateNameEn() *TicketCategoryUpsertBulk {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.UpdateNameEn()
	})
}

// SetActive sets the "active" field.
func (u *TicketCategoryUpsertBulk) SetActive(v bool) *TicketCategoryUpsertBulk {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *TicketCategoryUpsertBulk) UpdateActive() *TicketCategoryUpsertBulk {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.UpdateActive()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *TicketCategoryUpsertBulk) SetSortOrder(v int) *TicketCategoryUpsertBulk {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *TicketCategoryUpsertBulk) AddSortOrder(v int) *TicketCategoryUpsertBulk {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *TicketCategoryUpsertBulk) UpdateSortOrder() *TicketCategoryUpsertBulk {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TicketCategoryUpsertBulk) SetUpdatedAt(v time.Time) *TicketCategoryUpsertBulk {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TicketCategoryUpsertBulk) UpdateUpdatedAt() *TicketCategoryUpsertBulk {
	return u.Update(func(s *TicketCategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TicketCategoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TicketCategoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketCategoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketCategoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
