// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/ticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TicketMessageUpdate is the builder for updating TicketMessage entities.
type TicketMessageUpdate struct {
	config
	hooks    []Hook
	mutation *TicketMessageMutation
}

// Where appends a list predicates to the TicketMessageUpdate builder.
func (_u *TicketMessageUpdate) Where(ps ...predicate.TicketMessage) *TicketMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *TicketMessageUpdate) SetTicketID(v int64) *TicketMessageUpdate {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *TicketMessageUpdate) SetNillableTicketID(v *int64) *TicketMessageUpdate {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetSenderUserID sets the "sender_user_id" field.
func (_u *TicketMessageUpdate) SetSenderUserID(v int64) *TicketMessageUpdate {
	_u.mutation.SetSenderUserID(v)
	return _u
}

// SetNillableSenderUserID sets the "sender_user_id" field if the given value is not nil.
func (_u *TicketMessageUpdate) SetNillableSenderUserID(v *int64) *TicketMessageUpdate {
	if v != nil {
		_u.SetSenderUserID(*v)
	}
	return _u
}

// ClearSenderUserID clears the value of the "sender_user_id" field.
func (_u *TicketMessageUpdate) ClearSenderUserID() *TicketMessageUpdate {
	_u.mutation.ClearSenderUserID()
	return _u
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_u *TicketMessageUpdate) SetTicket(v *Ticket) *TicketMessageUpdate {
	return _u.SetTicketID(v.ID)
}

// SetSenderID sets the "sender" edge to the User entity by ID.
func (_u *TicketMessageUpdate) SetSenderID(id int64) *TicketMessageUpdate {
	_u.mutation.SetSenderID(id)
	return _u
}

// SetNillableSenderID sets the "sender" edge to the User entity by ID if the given value is not nil.
func (_u *TicketMessageUpdate) SetNillableSenderID(id *int64) *TicketMessageUpdate {
	if id != nil {
		_u = _u.SetSenderID(*id)
	}
	return _u
}

// SetSender sets the "sender" edge to the User entity.
func (_u *TicketMessageUpdate) SetSender(v *User) *TicketMessageUpdate {
	return _u.SetSenderID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the TicketAttachment entity by IDs.
func (_u *TicketMessageUpdate) AddAttachmentIDs(ids ...int64) *TicketMessageUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the TicketAttachment entity.
func (_u *TicketMessageUpdate) AddAttachments(v ...*TicketAttachment) *TicketMessageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the TicketMessageMutation object of the builder.
func (_u *TicketMessageUpdate) Mutation() *TicketMessageMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (_u *TicketMessageUpdate) ClearTicket() *TicketMessageUpdate {
	_u.mutation.ClearTicket()
	return _u
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *TicketMessageUpdate) ClearSender() *TicketMessageUpdate {
	_u.mutation.ClearSender()
	return _u
}

// ClearAttachments clears all "attachments" edges to the TicketAttachment entity.
func (_u *TicketMessageUpdate) ClearAttachments() *TicketMessageUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to TicketAttachment entities by IDs.
func (_u *TicketMessageUpdate) RemoveAttachmentIDs(ids ...int64) *TicketMessageUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to TicketAttachment entities.
func (_u *TicketMessageUpdate) RemoveAttachments(v ...*TicketAttachment) *TicketMessageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TicketMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TicketMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketMessageUpdate) check() error {
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketMessage.ticket"`)
	}
	return nil
}

func (_u *TicketMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketmessage.Table, ticketmessage.Columns, sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.TicketTable,
			Columns: []string{ticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.TicketTable,
			Columns: []string{ticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.SenderTable,
			Columns: []string{ticketmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.SenderTable,
			Columns: []string{ticketmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TicketMessageUpdateOne is the builder for updating a single TicketMessage entity.
type TicketMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TicketMessageMutation
}

// SetTicketID sets the "ticket_id" field.
func (_u *TicketMessageUpdateOne) SetTicketID(v int64) *TicketMessageUpdateOne {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *TicketMessageUpdateOne) SetNillableTicketID(v *int64) *TicketMessageUpdateOne {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetSenderUserID sets the "sender_user_id" field.
func (_u *TicketMessageUpdateOne) SetSenderUserID(v int64) *TicketMessageUpdateOne {
	_u.mutation.SetSenderUserID(v)
	return _u
}

// SetNillableSenderUserID sets the "sender_user_id" field if the given value is not nil.
func (_u *TicketMessageUpdateOne) SetNillableSenderUserID(v *int64) *TicketMessageUpdateOne {
	if v != nil {
		_u.SetSenderUserID(*v)
	}
	return _u
}

// ClearSenderUserID clears the value of the "sender_user_id" field.
func (_u *TicketMessageUpdateOne) ClearSenderUserID() *TicketMessageUpdateOne {
	_u.mutation.ClearSenderUserID()
	return _u
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_u *TicketMessageUpdateOne) SetTicket(v *Ticket) *TicketMessageUpdateOne {
	return _u.SetTicketID(v.ID)
}

// SetSenderID sets the "sender" edge to the User entity by ID.
func (_u *TicketMessageUpdateOne) SetSenderID(id int64) *TicketMessageUpdateOne {
	_u.mutation.SetSenderID(id)
	return _u
}

// SetNillableSenderID sets the "sender" edge to the User entity by ID if the given value is not nil.
func (_u *TicketMessageUpdateOne) SetNillableSenderID(id *int64) *TicketMessageUpdateOne {
	if id != nil {
		_u = _u.SetSenderID(*id)
	}
	return _u
}

// SetSender sets the "sender" edge to the User entity.
func (_u *TicketMessageUpdateOne) SetSender(v *User) *TicketMessageUpdateOne {
	return _u.SetSenderID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the TicketAttachment entity by IDs.
func (_u *TicketMessageUpdateOne) AddAttachmentIDs(ids ...int64) *TicketMessageUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the TicketAttachment entity.
func (_u *TicketMessageUpdateOne) AddAttachments(v ...*TicketAttachment) *TicketMessageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the TicketMessageMutation object of the builder.
func (_u *TicketMessageUpdateOne) Mutation() *TicketMessageMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (_u *TicketMessageUpdateOne) ClearTicket() *TicketMessageUpdateOne {
	_u.mutation.ClearTicket()
	return _u
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *TicketMessageUpdateOne) ClearSender() *TicketMessageUpdateOne {
	_u.mutation.ClearSender()
	return _u
}

// ClearAttachments clears all "attachments" edges to the TicketAttachment entity.
func (_u *TicketMessageUpdateOne) ClearAttachments() *TicketMessageUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to TicketAttachment entities by IDs.
func (_u *TicketMessageUpdateOne) RemoveAttachmentIDs(ids ...int64) *TicketMessageUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to TicketAttachment entities.
func (_u *TicketMessageUpdateOne) RemoveAttachments(v ...*TicketAttachment) *TicketMessageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Where appends a list predicates to the TicketMessageUpdate builder.
func (_u *TicketMessageUpdateOne) Where(ps ...predicate.TicketMessage) *TicketMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TicketMessageUpdateOne) Select(field string, fields ...string) *TicketMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TicketMessage entity.
func (_u *TicketMessageUpdateOne) Save(ctx context.Context) (*TicketMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketMessageUpdateOne) SaveX(ctx context.Context) *TicketMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TicketMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketMessageUpdateOne) check() error {
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketMessage.ticket"`)
	}
	return nil
}

func (_u *TicketMessageUpdateOne) sqlSave(ctx context.Context) (_node *TicketMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketmessage.Table, ticketmessage.Columns, sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TicketMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ticketmessage.FieldID)
		for _, f := range fields {
			if !ticketmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ticketmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.TicketTable,
			Columns: []string{ticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.TicketTable,
			Columns: []string{ticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.SenderTable,
			Columns: []string{ticketmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.SenderTable,
			Columns: []string{ticketmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TicketMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
