// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/ticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/ticketmessage"
)

// TicketAttachmentUpdate is the builder for updating TicketAttachment entities.
type TicketAttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *TicketAttachmentMutation
}

// Where appends a list predicates to the TicketAttachmentUpdate builder.
func (_u *TicketAttachmentUpdate) Where(ps ...predicate.TicketAttachment) *TicketAttachmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *TicketAttachmentUpdate) SetMessageID(v int64) *TicketAttachmentUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *TicketAttachmentUpdate) SetNillableMessageID(v *int64) *TicketAttachmentUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetMessage sets the "message" edge to the TicketMessage entity.
func (_u *TicketAttachmentUpdate) SetMessage(v *TicketMessage) *TicketAttachmentUpdate {
	return _u.SetMessageID(v.ID)
}

// Mutation returns the TicketAttachmentMutation object of the builder.
func (_u *TicketAttachmentUpdate) Mutation() *TicketAttachmentMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the TicketMessage entity.
func (_u *TicketAttachmentUpdate) ClearMessage() *TicketAttachmentUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TicketAttachmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketAttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TicketAttachmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketAttachmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketAttachmentUpdate) check() error {
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketAttachment.message"`)
	}
	return nil
}

func (_u *TicketAttachmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketattachment.Table, ticketattachment.Columns, sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketattachment.MessageTable,
			Columns: []string{ticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketattachment.MessageTable,
			Columns: []string{ticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TicketAttachmentUpdateOne is the builder for updating a single TicketAttachment entity.
type TicketAttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TicketAttachmentMutation
}

// SetMessageID sets the "message_id" field.
func (_u *TicketAttachmentUpdateOne) SetMessageID(v int64) *TicketAttachmentUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *TicketAttachmentUpdateOne) SetNillableMessageID(v *int64) *TicketAttachmentUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetMessage sets the "message" edge to the TicketMessage entity.
func (_u *TicketAttachmentUpdateOne) SetMessage(v *TicketMessage) *TicketAttachmentUpdateOne {
	return _u.SetMessageID(v.ID)
}

// Mutation returns the TicketAttachmentMutation object of the builder.
func (_u *TicketAttachmentUpdateOne) Mutation() *TicketAttachmentMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the TicketMessage entity.
func (_u *TicketAttachmentUpdateOne) ClearMessage() *TicketAttachmentUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// Where appends a list predicates to the TicketAttachmentUpdate builder.
func (_u *TicketAttachmentUpdateOne) Where(ps ...predicate.TicketAttachment) *TicketAttachmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TicketAttachmentUpdateOne) Select(field string, fields ...string) *TicketAttachmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TicketAttachment entity.
func (_u *TicketAttachmentUpdateOne) Save(ctx context.Context) (*TicketAttachment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketAttachmentUpdateOne) SaveX(ctx context.Context) *TicketAttachment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TicketAttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketAttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketAttachmentUpdateOne) check() error {
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketAttachment.message"`)
	}
	return nil
}

func (_u *TicketAttachmentUpdateOne) sqlSave(ctx context.Context) (_node *TicketAttachment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketattachment.Table, ticketattachment.Columns, sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TicketAttachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ticketattachment.FieldID)
		for _, f := range fields {
			if !ticketattachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ticketattachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketattachment.MessageTable,
			Columns: []string{ticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketattachment.MessageTable,
			Columns: []string{ticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TicketAttachment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
