// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TicketMessage is the model entity for the TicketMessage schema.
type TicketMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TicketID holds the value of the "ticket_id" field.
	TicketID int64 `json:"ticket_id,omitempty"`
	// SenderUserID holds the value of the "sender_user_id" field.
	SenderUserID *int64 `json:"sender_user_id,omitempty"`
	// SenderType holds the value of the "sender_type" field.
	SenderType string `json:"sender_type,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketMessageQuery when eager-loading is set.
	Edges        TicketMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TicketMessageEdges holds the relations/edges for other nodes in the graph.
type TicketMessageEdges struct {
	// Ticket holds the value of the ticket edge.
	Ticket *Ticket `json:"ticket,omitempty"`
	// Sender holds the value of the sender edge.
	Sender *User `json:"sender,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*TicketAttachment `json:"attachments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TicketOrErr returns the Ticket value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketMessageEdges) TicketOrErr() (*Ticket, error) {
	if e.Ticket != nil {
		return e.Ticket, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ticket.Label}
	}
	return nil, &NotLoadedError{edge: "ticket"}
}

// SenderOrErr returns the Sender value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketMessageEdges) SenderOrErr() (*User, error) {
	if e.Sender != nil {
		return e.Sender, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "sender"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e TicketMessageEdges) AttachmentsOrErr() ([]*TicketAttachment, error) {
	if e.loadedTypes[2] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TicketMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticketmessage.FieldID, ticketmessage.FieldTicketID, ticketmessage.FieldSenderUserID:
			values[i] = new(sql.NullInt64)
		case ticketmessage.FieldSenderType, ticketmessage.FieldEventType, ticketmessage.FieldContent:
			values[i] = new(sql.NullString)
		case ticketmessage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TicketMessage fields.
func (_m *TicketMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticketmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ticketmessage.FieldTicketID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_id", values[i])
			} else if value.Valid {
				_m.TicketID = value.Int64
			}
		case ticketmessage.FieldSenderUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sender_user_id", values[i])
			} else if value.Valid {
				_m.SenderUserID = new(int64)
				*_m.SenderUserID = value.Int64
			}
		case ticketmessage.FieldSenderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_type", values[i])
			} else if value.Valid {
				_m.SenderType = value.String
			}
		case ticketmessage.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case ticketmessage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case ticketmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TicketMessage.
// This includes values selected through modifiers, order, etc.
func (_m *TicketMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTicket queries the "ticket" edge of the TicketMessage entity.
func (_m *TicketMessage) QueryTicket() *TicketQuery {
	return NewTicketMessageClient(_m.config).QueryTicket(_m)
}

// QuerySender queries the "sender" edge of the TicketMessage entity.
func (_m *TicketMessage) QuerySender() *UserQuery {
	return NewTicketMessageClient(_m.config).QuerySender(_m)
}

// QueryAttachments queries the "attachments" edge of the TicketMessage entity.
func (_m *TicketMessage) QueryAttachments() *TicketAttachmentQuery {
	return NewTicketMessageClient(_m.config).QueryAttachments(_m)
}

// Update returns a builder for updating this TicketMessage.
// Note that you need to call TicketMessage.Unwrap() before calling this method if this TicketMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TicketMessage) Update() *TicketMessageUpdateOne {
	return NewTicketMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TicketMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TicketMessage) Unwrap() *TicketMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TicketMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TicketMessage) String() string {
	var builder strings.Builder
	builder.WriteString("TicketMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ticket_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TicketID))
	builder.WriteString(", ")
	if v := _m.SenderUserID; v != nil {
		builder.WriteString("sender_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("sender_type=")
	builder.WriteString(_m.SenderType)
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TicketMessages is a parsable slice of TicketMessage.
type TicketMessages []*TicketMessage
