export default {
  distribution: {
    agentCustomers: 'View customers',
    agentViewDetails: 'View agent details',
    agentEditRate: 'Adjust commission rate',
    agentPermissions: 'Manage permissions',
    agentRewards: 'Configure acquisition rewards',
    agentSuspend: 'Suspend agent',
    agentActivate: 'Reactivate agent',
    agentRevoke: 'Revoke agent',
    filterCurrent: 'Current filters',
    clearFilters: 'Clear all',
    anomalySeverityCritical: 'Critical',
    anomalySeverityHigh: 'High risk',
    anomalySeverityMedium: 'Needs attention',
    anomalyOverdueWithdrawal: 'Overdue withdrawal review',
    anomalyPendingFx: 'FX pending',
    anomalyAgentDebt: 'Agent wallet debt',
    anomalyInactiveCustomers: 'Inactive agent customers',
    anomalyMaturedCommission: 'Commission maturity delay',
    analytics: {
      overviewTitle: 'Distribution overview', overviewDescription: 'Acquisition, conversion, sales and commission analytics', channelTrend: 'Channel business trend', channelComposition: 'Channel composition', channelCompositionHint: 'Separate L1 direct customers from L2 team business', topAgents: 'Top L1 contributors', topAgentsHint: 'Ranked by customer payments in this period', allAgents: 'All agents', noAgentSales: 'No agent sales in this period', rankingCommission: 'Commission {amount}', liability: 'Commission liabilities and settlement', liabilityHint: 'Current platform payables and risks', ledger: 'View ledger', availableCommission: 'Available commission', frozenCommission: 'Frozen commission', reservedCommission: 'Reserved for settlement', registrationRewards: 'Period registration rewards', rechargeRewards: 'Period recharge rewards', paidThisMonth: 'Paid this month', reversals: 'Total reversals', agentDebt: 'Agent debt', operations: 'Operations queue', operationsHint: 'Prioritize items affecting agent settlement', reconciliation: 'Reconciliation', pendingWithdrawals: 'Pending review', payingWithdrawals: 'Payment processing', withdrawalTotal: 'Total {amount}', overdueReview: 'Review overdue', overdueHint: 'Not reviewed within 24 hours', maturity: 'Commission maturity', maturityRunning: 'Running', maturityHealthy: 'Healthy', maturityStandby: 'Standby', maturityError: 'Error', maturityDisabled: 'Disabled', maturityPending: 'Pending', maturityReleased: '{time}, released {count}', maturityWaiting: 'Waiting for first run', loadFailed: 'Failed to load distribution overview'
    },
    agentAnalytics: {
      emailMissing: 'Email not set', usernameMissing: 'Username not set', l1: 'L1 agent', l2: 'L2 agent', periodRate: 'Period new / paying', periodPaid: 'Period customer paid', periodCommission: 'Period commission', directTeam: 'Direct {direct} · Team {team}', rate: 'Commission rate', balance: 'Available / frozen', details: 'View agent details'
    },
    agents: {
      title: 'Agent management', description: 'Manage L1 agents and their team relationships', period: 'Business period', addL1: 'Add L1 agent', addL2: 'Add L2 agent', upgrade: 'Upgrade to agent', exportFiltered: 'Export current filters', export: 'Export', columnSettings: 'Column settings', resetColumns: 'Reset columns', searchPlaceholder: 'Search email, username or promotion code', search: 'Search agents', level: 'Agent level', allLevels: 'All levels', status: 'Agent status', allStatuses: 'All statuses', active: 'Active', suspended: 'Suspended', revoked: 'Revoked', currentFilters: 'Current filters', searchChip: 'Search: {query}', clearAll: 'Clear all', platformDirect: 'Platform direct', parent: 'Parent: {email}', unknown: 'Unknown', systemDefault: 'System default', customRate: 'Custom rate', payingCount: '{count} paying', newPayingRate: 'New / paying · {rate}', directTeam: 'Direct {direct} · Team {team}', directTeamCounts: 'Direct {directNew}/{directPaying} · Team {teamNew}/{teamPaying}', frozenAmount: 'Frozen {amount}', viewDetails: 'View details', noMatch: 'No matching agents', noMatchHint: 'Adjust filters or add the first L1 agent',
      stepLabel: 'Add agent steps', stepUser: 'Select user', stepRelation: 'Agent relation', stepBusiness: 'Business settings', selectUser: 'Select user', userPlaceholder: 'Enter user email or username', selectUserHint: 'Select an existing user. Customers already bound to an agent can be upgraded without rewriting historical attribution.', parentL1: 'Parent L1 agent', selectParent: 'Select L1 agent', upgradeHint: 'This user is currently bound to a distribution agent. Confirmation upgrades them to an {level} agent without changing historical orders or commission.', rate: 'Commission rate', defaultRateHint: 'Leave blank to use the system default rate of {rate}%', advanced: 'Advanced settings', customCode: 'Custom promotion code', autoCode: 'Leave blank to generate automatically', confirmConfig: 'Confirm agent settings', user: 'User', promotionCode: 'Promotion code', autoGenerate: 'Auto-generated', cancel: 'Cancel', previous: 'Previous', next: 'Next', adding: 'Adding...', confirmAdd: 'Confirm add',
      detailTitle: 'Agent details', detailDescription: 'Business data, permissions, rewards and audit history', detailPeriod: 'Detail business period', tabOverview: 'Business overview', tabCustomers: 'Customers and team', tabCommission: 'Commission and settlement', tabStrategy: 'Policy and permissions', tabAudit: 'Audit history', directBusiness: 'Direct business', teamBusiness: 'Team business', newPaying: 'New / paying', conversion: 'Conversion', customerPaid: 'Customer paid', directCommission: 'Direct commission', activeChildren: 'Active children', teamPaid: 'Team paid', teamCommission: 'Team commission', childRanking: 'Child agent contribution ranking', acquiredPaid: '{newCount} new · {payingCount} paying', availableCommission: 'Available commission', frozenCommission: 'Frozen commission', reservedCommission: 'Reserved for settlement', refundDebt: 'Refund debt', periodCommission: 'Period commission', cumulativeCommission: 'Cumulative commission', cumulativeWithdrawn: 'Cumulative withdrawn', convertedBalance: 'Converted to balance', recruitment: 'Child recruitment', promotionStats: 'Promotion analytics', authorized: 'Authorized', unauthorized: 'Unauthorized', viewable: 'Viewable', noPermission: 'No permission', changeLog: 'Change history', recentEvents: 'Latest {count}', system: 'System', noNote: 'No note', noEvents: 'No change history', closeStats: 'Disable analytics access', openStats: 'Enable analytics access', revokeRecruitment: 'Revoke recruitment', grantRecruitment: 'Grant recruitment', editRate: 'Edit commission rate', suspendAgent: 'Suspend agent', reactivateAgent: 'Reactivate', restoreAgent: 'Restore agent', revokeAgent: 'Revoke agent',
      statsCloseTitle: 'Disable promotion analytics access', statsOpenTitle: 'Enable promotion analytics access', statsCloseHint: 'The agent can still use promotion links but cannot view visit and conversion data.', statsOpenHint: 'The agent can view anonymous visit and registration conversion data for their promotion links.', operationReason: 'Operation reason', statsReasonPlaceholder: 'Record the basis for enabling or disabling access', saving: 'Saving...', confirm: 'Confirm', revokeRecruitmentHint: 'The agent can no longer add child agents; existing team relationships are unaffected.', grantRecruitmentHint: 'The L1 agent can add child agents using a complete email address.', recruitmentReasonPlaceholder: 'Record the basis for granting or revoking permission', currentEffective: 'Currently effective {rate} · {mode}', inheritDefault: 'Inherit system default', ratePolicy: 'Commission policy', changeReason: 'Change reason', changeReasonPlaceholder: 'Explain the basis for this rate adjustment', auditHint: 'The old and new rates and operator are written to the audit history', defaultRateValue: 'System default {rate}%', saveRate: 'Save rate', statusReasonPlaceholder: 'Record the reason for this status change', processing: 'Processing...',
      statusReenableTitle: 'Reactivate agent', statusRestoreTitle: 'Restore agent', statusSuspendTitle: 'Suspend agent', statusRevokeTitle: 'Revoke agent', revokeMessage: 'After revocation, this agent cannot create new customer or commission relationships. An administrator can reactivate it later.', suspendMessage: 'Suspension stops new customer bindings and commission accrual.', reenableMessage: 'After reactivation, the agent can use the original promotion link and earn commission. Enter a reason for reactivation.', restoreMessage: 'After restoration, the agent can use the promotion link and earn commission.',
      colUser: 'Agent user', colRelation: 'Hierarchy', colCustomers: 'Customers / paying', colPeriodCustomers: 'Period new / paying', colRate: 'Commission policy', colPaid: 'Customer paid', colCommission: 'Commission income', colBalance: 'Commission balance', colStatus: 'Status', colActions: 'Actions', userInactive: 'User is inactive', alreadyAgent: 'Already an agent', distributionCustomer: 'Bound to an agent', affiliateInvitee: 'Bound to an inviter', userNormal: 'User active', unavailable: 'Currently unavailable', loadFailed: 'Failed to load agents', exportSuccess: 'Agent data exported', exportFailed: 'Failed to export agents', loadDefaultsFailed: 'Failed to load default commission settings', selectParentError: 'Select a parent L1 agent', rateRangeError: 'Commission rate must be between 0% and 100%', upgraded: 'User upgraded to agent', added: '{level} agent added', addFailed: 'Failed to add agent', loadRateFailed: 'Failed to load commission settings', loadEventsFailed: 'Failed to load agent change history', loadAnalyticsFailed: 'Failed to load agent analytics', createdEvent: 'Agent created', statsGrantedEvent: 'Promotion analytics access enabled', statsRevokedEvent: 'Promotion analytics access disabled', recruitmentGrantedEvent: 'Child recruitment granted', recruitmentRevokedEvent: 'Child recruitment revoked', rateEvent: 'Commission rate {before} → {after}', recruitmentGranted: 'Child recruitment granted', recruitmentRevoked: 'Child recruitment revoked', recruitmentUpdateFailed: 'Failed to update recruitment permission', statsGranted: 'Promotion analytics access enabled', statsRevoked: 'Promotion analytics access disabled', statsUpdateFailed: 'Failed to update promotion analytics access', statusUpdated: 'Agent status updated', statusUpdateFailed: 'Failed to update status', rateUpdated: 'Commission rate updated', rateUpdateFailed: 'Failed to update commission rate'
    },
  },
}
