// Code generated by ent, DO NOT EDIT.

package ticketmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// SenderUserID applies equality check predicate on the "sender_user_id" field. It's identical to SenderUserIDEQ.
func SenderUserID(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldSenderUserID, v))
}

// SenderType applies equality check predicate on the "sender_type" field. It's identical to SenderTypeEQ.
func SenderType(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldSenderType, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldEventType, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldTicketID, vs...))
}

// SenderUserIDEQ applies the EQ predicate on the "sender_user_id" field.
func SenderUserIDEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldSenderUserID, v))
}

// SenderUserIDNEQ applies the NEQ predicate on the "sender_user_id" field.
func SenderUserIDNEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldSenderUserID, v))
}

// SenderUserIDIn applies the In predicate on the "sender_user_id" field.
func SenderUserIDIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldSenderUserID, vs...))
}

// SenderUserIDNotIn applies the NotIn predicate on the "sender_user_id" field.
func SenderUserIDNotIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldSenderUserID, vs...))
}

// SenderUserIDIsNil applies the IsNil predicate on the "sender_user_id" field.
func SenderUserIDIsNil() predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIsNull(FieldSenderUserID))
}

// SenderUserIDNotNil applies the NotNil predicate on the "sender_user_id" field.
func SenderUserIDNotNil() predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotNull(FieldSenderUserID))
}

// SenderTypeEQ applies the EQ predicate on the "sender_type" field.
func SenderTypeEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldSenderType, v))
}

// SenderTypeNEQ applies the NEQ predicate on the "sender_type" field.
func SenderTypeNEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldSenderType, v))
}

// SenderTypeIn applies the In predicate on the "sender_type" field.
func SenderTypeIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldSenderType, vs...))
}

// SenderTypeNotIn applies the NotIn predicate on the "sender_type" field.
func SenderTypeNotIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldSenderType, vs...))
}

// SenderTypeGT applies the GT predicate on the "sender_type" field.
func SenderTypeGT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldSenderType, v))
}

// SenderTypeGTE applies the GTE predicate on the "sender_type" field.
func SenderTypeGTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldSenderType, v))
}

// SenderTypeLT applies the LT predicate on the "sender_type" field.
func SenderTypeLT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldSenderType, v))
}

// SenderTypeLTE applies the LTE predicate on the "sender_type" field.
func SenderTypeLTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldSenderType, v))
}

// SenderTypeContains applies the Contains predicate on the "sender_type" field.
func SenderTypeContains(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContains(FieldSenderType, v))
}

// SenderTypeHasPrefix applies the HasPrefix predicate on the "sender_type" field.
func SenderTypeHasPrefix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasPrefix(FieldSenderType, v))
}

// SenderTypeHasSuffix applies the HasSuffix predicate on the "sender_type" field.
func SenderTypeHasSuffix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasSuffix(FieldSenderType, v))
}

// SenderTypeEqualFold applies the EqualFold predicate on the "sender_type" field.
func SenderTypeEqualFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEqualFold(FieldSenderType, v))
}

// SenderTypeContainsFold applies the ContainsFold predicate on the "sender_type" field.
func SenderTypeContainsFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContainsFold(FieldSenderType, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContainsFold(FieldEventType, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContainsFold(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.Ticket) predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := newTicketStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSender applies the HasEdge predicate on the "sender" edge.
func HasSender() predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SenderTable, SenderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSenderWith applies the HasEdge predicate on the "sender" edge with a given conditions (other predicates).
func HasSenderWith(preds ...predicate.User) predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := newSenderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttachments applies the HasEdge predicate on the "attachments" edge.
func HasAttachments() predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentsWith applies the HasEdge predicate on the "attachments" edge with a given conditions (other predicates).
func HasAttachmentsWith(preds ...predicate.TicketAttachment) predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := newAttachmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TicketMessage) predicate.TicketMessage {
	return predicate.TicketMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TicketMessage) predicate.TicketMessage {
	return predicate.TicketMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TicketMessage) predicate.TicketMessage {
	return predicate.TicketMessage(sql.NotPredicates(p))
}
