// Code generated by ent, DO NOT EDIT.

package ticketattachment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldID, id))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldMessageID, v))
}

// ObjectKey applies equality check predicate on the "object_key" field. It's identical to ObjectKeyEQ.
func ObjectKey(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldObjectKey, v))
}

// OriginalName applies equality check predicate on the "original_name" field. It's identical to OriginalNameEQ.
func OriginalName(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldOriginalName, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldContentType, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldSizeBytes, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldSha256, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldCreatedAt, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldMessageID, vs...))
}

// ObjectKeyEQ applies the EQ predicate on the "object_key" field.
func ObjectKeyEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldObjectKey, v))
}

// ObjectKeyNEQ applies the NEQ predicate on the "object_key" field.
func ObjectKeyNEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldObjectKey, v))
}

// ObjectKeyIn applies the In predicate on the "object_key" field.
func ObjectKeyIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldObjectKey, vs...))
}

// ObjectKeyNotIn applies the NotIn predicate on the "object_key" field.
func ObjectKeyNotIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldObjectKey, vs...))
}

// ObjectKeyGT applies the GT predicate on the "object_key" field.
func ObjectKeyGT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldObjectKey, v))
}

// ObjectKeyGTE applies the GTE predicate on the "object_key" field.
func ObjectKeyGTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldObjectKey, v))
}

// ObjectKeyLT applies the LT predicate on the "object_key" field.
func ObjectKeyLT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldObjectKey, v))
}

// ObjectKeyLTE applies the LTE predicate on the "object_key" field.
func ObjectKeyLTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldObjectKey, v))
}

// ObjectKeyContains applies the Contains predicate on the "object_key" field.
func ObjectKeyContains(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContains(FieldObjectKey, v))
}

// ObjectKeyHasPrefix applies the HasPrefix predicate on the "object_key" field.
func ObjectKeyHasPrefix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasPrefix(FieldObjectKey, v))
}

// ObjectKeyHasSuffix applies the HasSuffix predicate on the "object_key" field.
func ObjectKeyHasSuffix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasSuffix(FieldObjectKey, v))
}

// ObjectKeyEqualFold applies the EqualFold predicate on the "object_key" field.
func ObjectKeyEqualFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEqualFold(FieldObjectKey, v))
}

// ObjectKeyContainsFold applies the ContainsFold predicate on the "object_key" field.
func ObjectKeyContainsFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContainsFold(FieldObjectKey, v))
}

// OriginalNameEQ applies the EQ predicate on the "original_name" field.
func OriginalNameEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldOriginalName, v))
}

// OriginalNameNEQ applies the NEQ predicate on the "original_name" field.
func OriginalNameNEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldOriginalName, v))
}

// OriginalNameIn applies the In predicate on the "original_name" field.
func OriginalNameIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldOriginalName, vs...))
}

// OriginalNameNotIn applies the NotIn predicate on the "original_name" field.
func OriginalNameNotIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldOriginalName, vs...))
}

// OriginalNameGT applies the GT predicate on the "original_name" field.
func OriginalNameGT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldOriginalName, v))
}

// OriginalNameGTE applies the GTE predicate on the "original_name" field.
func OriginalNameGTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldOriginalName, v))
}

// OriginalNameLT applies the LT predicate on the "original_name" field.
func OriginalNameLT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldOriginalName, v))
}

// OriginalNameLTE applies the LTE predicate on the "original_name" field.
func OriginalNameLTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldOriginalName, v))
}

// OriginalNameContains applies the Contains predicate on the "original_name" field.
func OriginalNameContains(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContains(FieldOriginalName, v))
}

// OriginalNameHasPrefix applies the HasPrefix predicate on the "original_name" field.
func OriginalNameHasPrefix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasPrefix(FieldOriginalName, v))
}

// OriginalNameHasSuffix applies the HasSuffix predicate on the "original_name" field.
func OriginalNameHasSuffix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasSuffix(FieldOriginalName, v))
}

// OriginalNameEqualFold applies the EqualFold predicate on the "original_name" field.
func OriginalNameEqualFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEqualFold(FieldOriginalName, v))
}

// OriginalNameContainsFold applies the ContainsFold predicate on the "original_name" field.
func OriginalNameContainsFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContainsFold(FieldOriginalName, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContainsFold(FieldContentType, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldSizeBytes, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContainsFold(FieldSha256, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldCreatedAt, v))
}

// HasMessage applies the HasEdge predicate on the "message" edge.
func HasMessage() predicate.TicketAttachment {
	return predicate.TicketAttachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MessageTable, MessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageWith applies the HasEdge predicate on the "message" edge with a given conditions (other predicates).
func HasMessageWith(preds ...predicate.TicketMessage) predicate.TicketAttachment {
	return predicate.TicketAttachment(func(s *sql.Selector) {
		step := newMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TicketAttachment) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TicketAttachment) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TicketAttachment) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.NotPredicates(p))
}
