// Code generated by ent, DO NOT EDIT.

package appauthorization

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldUserID, v))
}

// GrantID applies equality check predicate on the "grant_id" field. It's identical to GrantIDEQ.
func GrantID(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldGrantID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldClientID, v))
}

// DeviceName applies equality check predicate on the "device_name" field. It's identical to DeviceNameEQ.
func DeviceName(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldDeviceName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldPlatform, v))
}

// TokenFamilyID applies equality check predicate on the "token_family_id" field. It's identical to TokenFamilyIDEQ.
func TokenFamilyID(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldTokenFamilyID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldStatus, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldLastUsedAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLTE(FieldUserID, v))
}

// GrantIDEQ applies the EQ predicate on the "grant_id" field.
func GrantIDEQ(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldGrantID, v))
}

// GrantIDNEQ applies the NEQ predicate on the "grant_id" field.
func GrantIDNEQ(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNEQ(FieldGrantID, v))
}

// GrantIDIn applies the In predicate on the "grant_id" field.
func GrantIDIn(vs ...string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIn(FieldGrantID, vs...))
}

// GrantIDNotIn applies the NotIn predicate on the "grant_id" field.
func GrantIDNotIn(vs ...string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotIn(FieldGrantID, vs...))
}

// GrantIDGT applies the GT predicate on the "grant_id" field.
func GrantIDGT(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGT(FieldGrantID, v))
}

// GrantIDGTE applies the GTE predicate on the "grant_id" field.
func GrantIDGTE(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGTE(FieldGrantID, v))
}

// GrantIDLT applies the LT predicate on the "grant_id" field.
func GrantIDLT(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLT(FieldGrantID, v))
}

// GrantIDLTE applies the LTE predicate on the "grant_id" field.
func GrantIDLTE(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLTE(FieldGrantID, v))
}

// GrantIDContains applies the Contains predicate on the "grant_id" field.
func GrantIDContains(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldContains(FieldGrantID, v))
}

// GrantIDHasPrefix applies the HasPrefix predicate on the "grant_id" field.
func GrantIDHasPrefix(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldHasPrefix(FieldGrantID, v))
}

// GrantIDHasSuffix applies the HasSuffix predicate on the "grant_id" field.
func GrantIDHasSuffix(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldHasSuffix(FieldGrantID, v))
}

// GrantIDEqualFold applies the EqualFold predicate on the "grant_id" field.
func GrantIDEqualFold(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEqualFold(FieldGrantID, v))
}

// GrantIDContainsFold applies the ContainsFold predicate on the "grant_id" field.
func GrantIDContainsFold(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldContainsFold(FieldGrantID, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldContainsFold(FieldClientID, v))
}

// DeviceNameEQ applies the EQ predicate on the "device_name" field.
func DeviceNameEQ(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldDeviceName, v))
}

// DeviceNameNEQ applies the NEQ predicate on the "device_name" field.
func DeviceNameNEQ(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNEQ(FieldDeviceName, v))
}

// DeviceNameIn applies the In predicate on the "device_name" field.
func DeviceNameIn(vs ...string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIn(FieldDeviceName, vs...))
}

// DeviceNameNotIn applies the NotIn predicate on the "device_name" field.
func DeviceNameNotIn(vs ...string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotIn(FieldDeviceName, vs...))
}

// DeviceNameGT applies the GT predicate on the "device_name" field.
func DeviceNameGT(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGT(FieldDeviceName, v))
}

// DeviceNameGTE applies the GTE predicate on the "device_name" field.
func DeviceNameGTE(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGTE(FieldDeviceName, v))
}

// DeviceNameLT applies the LT predicate on the "device_name" field.
func DeviceNameLT(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLT(FieldDeviceName, v))
}

// DeviceNameLTE applies the LTE predicate on the "device_name" field.
func DeviceNameLTE(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLTE(FieldDeviceName, v))
}

// DeviceNameContains applies the Contains predicate on the "device_name" field.
func DeviceNameContains(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldContains(FieldDeviceName, v))
}

// DeviceNameHasPrefix applies the HasPrefix predicate on the "device_name" field.
func DeviceNameHasPrefix(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldHasPrefix(FieldDeviceName, v))
}

// DeviceNameHasSuffix applies the HasSuffix predicate on the "device_name" field.
func DeviceNameHasSuffix(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldHasSuffix(FieldDeviceName, v))
}

// DeviceNameEqualFold applies the EqualFold predicate on the "device_name" field.
func DeviceNameEqualFold(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEqualFold(FieldDeviceName, v))
}

// DeviceNameContainsFold applies the ContainsFold predicate on the "device_name" field.
func DeviceNameContainsFold(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldContainsFold(FieldDeviceName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldContainsFold(FieldPlatform, v))
}

// TokenFamilyIDEQ applies the EQ predicate on the "token_family_id" field.
func TokenFamilyIDEQ(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldTokenFamilyID, v))
}

// TokenFamilyIDNEQ applies the NEQ predicate on the "token_family_id" field.
func TokenFamilyIDNEQ(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNEQ(FieldTokenFamilyID, v))
}

// TokenFamilyIDIn applies the In predicate on the "token_family_id" field.
func TokenFamilyIDIn(vs ...string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIn(FieldTokenFamilyID, vs...))
}

// TokenFamilyIDNotIn applies the NotIn predicate on the "token_family_id" field.
func TokenFamilyIDNotIn(vs ...string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotIn(FieldTokenFamilyID, vs...))
}

// TokenFamilyIDGT applies the GT predicate on the "token_family_id" field.
func TokenFamilyIDGT(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGT(FieldTokenFamilyID, v))
}

// TokenFamilyIDGTE applies the GTE predicate on the "token_family_id" field.
func TokenFamilyIDGTE(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGTE(FieldTokenFamilyID, v))
}

// TokenFamilyIDLT applies the LT predicate on the "token_family_id" field.
func TokenFamilyIDLT(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLT(FieldTokenFamilyID, v))
}

// TokenFamilyIDLTE applies the LTE predicate on the "token_family_id" field.
func TokenFamilyIDLTE(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLTE(FieldTokenFamilyID, v))
}

// TokenFamilyIDContains applies the Contains predicate on the "token_family_id" field.
func TokenFamilyIDContains(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldContains(FieldTokenFamilyID, v))
}

// TokenFamilyIDHasPrefix applies the HasPrefix predicate on the "token_family_id" field.
func TokenFamilyIDHasPrefix(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldHasPrefix(FieldTokenFamilyID, v))
}

// TokenFamilyIDHasSuffix applies the HasSuffix predicate on the "token_family_id" field.
func TokenFamilyIDHasSuffix(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldHasSuffix(FieldTokenFamilyID, v))
}

// TokenFamilyIDEqualFold applies the EqualFold predicate on the "token_family_id" field.
func TokenFamilyIDEqualFold(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEqualFold(FieldTokenFamilyID, v))
}

// TokenFamilyIDContainsFold applies the ContainsFold predicate on the "token_family_id" field.
func TokenFamilyIDContainsFold(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldContainsFold(FieldTokenFamilyID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldContainsFold(FieldStatus, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotNull(FieldLastUsedAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.FieldNotNull(FieldRevokedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppAuthorization) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppAuthorization) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppAuthorization) predicate.AppAuthorization {
	return predicate.AppAuthorization(sql.NotPredicates(p))
}
