export default { business: {
  usageHistoryIncomplete:'当前仅可恢复自 {date} 起的成功计费用量；更早范围内的活跃、模型消费、供应商成本和留存数据可能不完整。',
  granularity_hour:'按小时',granularity_day:'按日',granularity_week:'按周',granularity_month:'按月',
  d7Retention:'D7 留存',lifecycle:'用户生命周期',lifecycleHint:'按当前周期活跃行为划分',lifecycle_new:'新增',lifecycle_active:'活跃',lifecycle_silent:'沉默',lifecycle_churned:'流失',lifecycle_recalled:'召回',
  analysisScope:'分析范围',agentSearchPlaceholder:'输入代理邮箱或推广码',customerScope:'客户范围',teamCustomers:'团队客户',directCustomers:'直属客户',currentBindingHint:'按当前客户绑定关系统计',levelOneAgent:'一级代理',levelTwoAgent:'二级代理',title:'经营分析',overview:'经营总览',growth:'用户增长',finance:'收入与成本',retention:'留存与生命周期',channels:'渠道分析',
  overviewTitle:'经营总览',growthTitle:'用户增长',financeTitle:'收入与成本',retentionTitle:'留存与生命周期',channelsTitle:'渠道分析',
  operationTrend:'经营趋势',userTrend:'用户增长趋势',financeTrend:'收入与消费趋势',channelTrend:'渠道贡献趋势',metric:'指标',channel:'渠道',allChannels:'全部渠道',updating:'正在更新数据…',noData:'当前周期暂无数据',loadFailed:'加载经营分析失败',noComparison:'暂无上期基准',vsPrevious:'较上期 {value}',pointsChange:'较上期 {value} 个百分点',turnedPositive:'较上期转正',turnedNegative:'较上期转负',previous:'上期',periodValue:'本期',estimatedFx:'包含估算汇率',updatedAt:'更新于 {time}',exportData:'导出数据',timeBucket:'时间',
  netPaid:'净实付',newUsers:'新增用户',activeUsers:'活跃用户',consumedRevenue:'模型消费收入',supplierCost:'供应商成本',funnel:'新用户转化',funnelHint:'首次模型调用和首次付款均以新增注册为基准，再次付款以首付用户为基准',funnel_registered:'新增注册',funnelRateOfRegistered:'占新增 {value}',funnelRateOfFirstPaid:'占首付 {value}',funnel_activated:'首次模型调用',funnel_first_paid:'首次付款',funnel_repurchased:'再次实付',growthStructure:'用户增长构成',growthStructureHint:'当前周期关键生命周期节点',cashBusiness:'现金经营',consumptionProfit:'消费利润',cashHint:'支付平台实收与实际退款，统一折算人民币',profitHint:'成功计费请求收入减供应商账号成本，统一使用 USD 计价',retentionMatrix:'留存矩阵',retentionHint:'尚未到达 D1、D7 或 D30 的用户批次显示为空',registrationRetention:'注册留存',activationRetention:'首次使用留存',registrationDate:'注册日期',firstUseDate:'首次使用日期',registeredUsers:'注册用户数',firstUseUsers:'首次使用用户数',channelComparison:'渠道经营对比',channelComparisonHint:'点击分销渠道可下钻到分销经营分析',
  conversionTime:'转化耗时分布',conversionTimeHint:'当前周期注册用户到首次模型调用和首次付款的耗时',duration_under_1h:'1 小时内',duration_1h_24h:'1–24 小时',duration_1d_3d:'1–3 天',duration_3d_7d:'3–7 天',duration_over_7d:'7 天以上',originalCurrency:'原币明细',originalCurrencyHint:'原币金额不受报告币种折算影响',currency:'币种',
  channel_distribution:'分销',channel_affiliate:'旧邀请',channel_campaign:'活动',channel_organic:'自然',channel_unknown:'未知',activatedUsers:'首次使用用户',firstPaidUsers:'首付用户',repurchaseRate:'复购率',arppu:'ARPPU',
  metric_new_users:'新增用户',metric_activated_users:'首次使用用户',metric_first_paid_users:'首付用户',metric_paying_users:'付费用户',metric_repurchase_users:'复购用户',metric_active_users:'活跃用户',metric_paid_conversion_rate:'付费转化率',metric_repurchase_rate:'复购率',metric_active_rate:'活跃率',metric_gross_paid:'毛实付',metric_refunded:'退款金额',metric_net_paid:'净实付',metric_refund_rate:'退款率',metric_arpu:'ARPU',metric_arppu:'ARPPU',metric_consumed_revenue:'模型消费收入',metric_supplier_cost:'供应商成本',metric_consumption_profit:'消费毛利',metric_consumption_margin_rate:'消费毛利率',metric_commission_cost_rate:'佣金成本率',metric_reward_cost_rate:'奖励成本率',
  revenueTrend:'收入趋势',difference:'差额',userBalance:'用户余额',balanceHint:'全平台当前用户额度及生命周期状态，不作为现金收入或消费利润',balanceWindow1:'今日',balanceWindow7:'近 7 天',balanceWindow30:'近 30 天',balanceAsOf:'余额更新于 {time}',balanceCurrentHint:'余额为查询时的实时 USD 平台额度，人民币参考值按当前余额充值倍率反推；生命周期状态截至今天。',balanceLoadFailed:'加载用户余额失败',availableBalance:'可用余额',frozenBalance:'冻结余额',positiveBalanceUsers:'有余额用户',averageBalance:'户均可用余额',lowBalanceUsers:'低余额用户',users:'用户数',balanceSegment_active:'活跃',balanceSegment_silent:'沉默',balanceSegment_churned:'流失',balanceSegment_unactivated:'从未使用',lifecycle_unactivated:'从未使用',lifecycleActiveDetail:'首次使用 {newly} · 持续活跃 {continuous}',lifecycleRecallDetail:'沉默唤醒 {silent} · 流失召回 {churned}',
  help_new_users:'所选周期内完成注册的用户数。生命周期中新增优先归类，不与其他分群重复。',help_activated_users:'首次使用模型并产生成功计费请求的时间落在所选周期内的用户数。',help_first_paid_users:'首次有效实付发生在所选周期内的用户数。',help_paying_users:'所选周期内至少完成一次有效实付的去重用户数。',help_repurchase_users:'所选周期内再次实付，且周期开始前已有有效实付记录的用户数。',help_active_users:'所选周期内至少产生一次成功计费推理请求的去重用户数。主动检测、失败请求和非推理请求不计入。',help_paid_conversion_rate:'所选周期新增注册用户中，截至周期结束已完成首次有效实付的比例。',help_repurchase_rate:'所选周期复购用户数除以全部付费用户数。',help_active_rate:'所选周期活跃用户数除以截至周期结束纳入统计的用户数。',help_gross_paid:'支付平台在所选周期确认收款的金额，按支付时汇率折算为人民币。',help_refunded:'所选周期实际发生的退款金额，按原支付汇率折算为人民币。',help_net_paid:'毛实付减实际退款，反映所选周期净现金流入。',help_refund_rate:'退款金额除以毛实付金额。',help_arpu:'净实付除以活跃用户数。',help_arppu:'净实付除以付费用户数。',help_consumed_revenue:'所选周期成功计费推理请求实际扣除的用户余额总额，使用 USD 计价，不等同于充值实付；如需人民币参考值，应除以余额充值倍率。',help_supplier_cost:'所选周期成功请求对应的供应商实际成本，已包含账号倍率，使用 USD 计价。',help_consumption_profit:'模型消费收入减供应商成本，使用 USD 计价。',help_consumption_margin_rate:'消费毛利除以模型消费收入。',help_commission_cost_rate:'分销佣金成本除以净实付。',help_reward_cost_rate:'注册及充值达标奖励成本除以净实付。',help_available_balance:'所有有效用户当前可用 USD 平台额度总额，不属于已实现收入。',help_frozen_balance:'所有有效用户当前冻结 USD 平台额度总额。',help_positive_balance_users:'当前可用余额大于零的用户数。',help_average_balance:'当前可用余额总额除以全部有效用户数。',help_low_balance_users:'当前可用余额低于用户有效提醒阈值的用户数；仅在系统低余额提醒启用时显示。',help_lifecycle_new:'周期内注册的用户，优先归入新增，不再进入其他生命周期分群。',help_lifecycle_active:'非新增用户中，本期首次使用模型或本期与等长上期均活跃的用户。',help_lifecycle_recalled:'非新增、本期活跃而等长上期不活跃且历史活跃过的用户；离开不超过 30 天为沉默唤醒，超过 30 天为流失召回。',help_lifecycle_silent:'本期不活跃，且截至周期结束距最后一次成功计费请求不超过 30 天。',help_lifecycle_churned:'本期不活跃，且截至周期结束距最后一次成功计费请求超过 30 天。',help_lifecycle_unactivated:'周期开始前注册，且截至周期结束从未产生成功计费推理请求的用户。'
} }
